// 특수 기능(SpecialTools) 도구 정의 — 화면 렌더와 권한 매트릭스 편집이 공유하는 단일 소스.
// k(권한 키의 대상)·label·icon·desc + 플래그(adminOnly/disabled/comingSoon/danger/external).
// external: 이 포탈의 화면이 아니라 다른 포탈을 새 탭으로 여는 항목. 주소는 서버가
// 인증 후에만 내려주므로(`/auth/me` serviceHubUrl), 미설정이면 카드 자체가 나오지 않는다.
export const TOOLS = [
  { k: 'service-hub', icon: '🧰', label: '서비스 허브 (별도 포탈)', desc: '운영 서비스 바로가기 모음 · 링크 상태 점검/추이 · 데이터센터 구성 (새 탭)', external: 'serviceHubUrl' },
  { k: 'aisearch', icon: '🔎', label: 'AI 검색 (자연어)', desc: '자연어로 VM/호스트/IP 검색 · 로컬 LLM' },
  { k: 'insights', icon: '🧠', label: '운영 인사이트', desc: 'VM 라이트사이징 · 클러스터 N+1 여력 · 알람 핫스팟 · GPU 유휴' },
  { k: 'explore', icon: '🏆', label: '탐색·랭킹', desc: '자원 최다 사용 Top 랭킹(CPU·메모리·디스크·전력) + 상세 스펙 VM 검색 — 리전/vCenter 범위 선택', perm: 'dashboard' },
  { k: 'threats', icon: '🛡️', label: '위협 탐지', desc: '마이닝 의심 · 위험 포트 노출 · EOL OS · 신규 rogue IP · NSX IDS' },
  { k: 'secret-scan', icon: '🔐', label: '평문 자격증명 점검', desc: '설정 파일·portal.env·로그·소스에 평문으로 남은 계정정보/토큰/키 탐지(값은 마스킹) · 암호화 저장 전환 안내', adminOnly: true },
  { k: 'codex-check', icon: '🛡️', label: '보안점검', desc: '프로그램 보안·완성도 점검 리포트 — 외부 전수 점검 결과 + 실시간 지표 · Markdown 저장/다운로드', adminOnly: true },
  { k: 'vm-clone', icon: '🧬', label: 'VM 복제(백업)', desc: 'vCenter별 VM 지정 → 스냅샷 시점 복제(무중단) · 스케줄 정기 실행 · 대상 데이터스토어/NFS 선택 · 최근 N개 보존 · 트리에 Clone 배지', adminOnly: true },
  { k: 'storage-mon', icon: '🗄️', label: '스토리지 모니터링', desc: '글로벌 법인 스토리지 8종(PowerScale/Isilon·PowerStore·Unity·XtremIO·VMAX/PowerMax·VPLEX/Metro Node) 사용량·버전·노드 통합 조회 · 용량 시계열/추이 · 엣지 현지 수집→중앙 집계 · 법인별/타입별 뷰', adminOnly: true },
  { k: 'bm-storage', icon: '💽', label: '베어메탈 스토리지', desc: '서버 SSH(df)로 로컬 디스크 마운트 포인트 용량 수집 · 서버/그룹/전체 합산(총·사용·가용) · 사용자 지정 주기 · 엣지 위임(중앙→엣지 PUSH)', adminOnly: true },
  { k: 'vmfinder', icon: '🧭', label: 'VM 정밀 검색 / 유휴 VM', desc: '다수 vCenter·폴더·클러스터·풀 + 조건 · 1일/1주 평균 CPU로 미사용 VM' },
  { k: 'deepsearch', icon: '🔭', label: '심층 검색', desc: '게이트웨이·서브넷·GPU·OS 등 다조건 + 게스트 탐침(GPU드라이버·프로세스) · 전체/복수 vCenter' },
  { k: 'capacity', icon: '📈', label: '용량 리포트', desc: '클러스터별 여유·오버커밋·수용여력 · 전체/법인별' },
  { k: 'waste', icon: '♻️', label: '낭비 리소스', desc: '정지 VM·스냅샷·thin 회수가능·Tools 미설치' },
  { k: 'esxitemp', icon: '🌡️', label: 'ESXi 온도', desc: '호스트/클러스터/법인별 현재 온도 + 최근 5년 추이' },
  { k: 'forecast', icon: '🔮', label: '용량 추세/예측', desc: '데이터스토어 증가율·가득 찰 예상일' },
  { k: 'dsusage', icon: '💽', label: 'vCenter별 스토리지', desc: 'DataCenter/vCenter별 데이터스토어 연결 현황 · 가용/전체 용량' },
  { k: 'guestos', icon: '🐧', label: 'Guest OS 종류/버전', desc: 'OS·버전별 VM 수 · 전체/법인별 · 검색' },
  { k: 'real-os', icon: '🔎', label: '실제 OS 확인(게스트)', desc: '게스트 OS에서 실제 설치 OS(/etc/os-release 등) 읽기 · ESXi 보고와 불일치 탐지 · 주기 스캔 · CSV' },
  { k: 'thinvms', icon: '💧', label: 'Thin VM 찾기', desc: 'Thin 프로비저닝 VM · 회수 가능 용량(추정)' },
  { k: 'vm-export', icon: '📤', label: 'VM 전체 정보 CSV', desc: '선택 vCenter 모든 VM 의 최대 상세(호스트·클러스터/CPU·코어/메모리/NIC·MAC·IP/디스크 1~7 슬롯별 용량·타입·데이터스토어·파일/게스트 파티션 사용량/스냅샷/Tools/UUID 등 85+ 컬럼)를 CSV 로 내보내기' },
  // ipam 은 상단 'IP관리' 탭으로 승격(v2.274, 화면은 SpecialTools.jsx IpamStandalone). topTab:
  // 특수 기능 카드 그리드에는 안 보이지만 항목은 유지 — 권한 매트릭스(사용자 관리 › 도구별 접근)의
  // toolsDenied 'ipam' 키 편집 UI 가 이 목록에서 나오고, 그 값이 상단 탭 노출(App.jsx toolKey)을 결정한다.
  { k: 'ipam', icon: '📒', label: 'IP관리 (상단 메뉴)', desc: '상단 IP관리 탭으로 이동 — 여기서의 접근 차단이 상단 탭 노출에 그대로 적용됩니다.', topTab: true },
  { k: 'dupip', icon: '🔁', label: '중복 IP 찾기', desc: '둘 이상 VM이 같은 IPv4를 쓰는 경우' },
  { k: 'vmtools', icon: '🧩', label: 'VMware Tools 버전', desc: '버전별 집계 + 업그레이드' },
  { k: 'snapshots', icon: '📸', label: '스냅샷 있는 VM', desc: 'vCenter/용량/개수별 정렬' },
  { k: 'daily-health', icon: '📋', label: '일일 헬스체크 리포트', desc: 'vCheck 스타일 아침 점검 — 스냅샷·용량·Tools·연결·인증서 요약 + 매일 지정 시각 웹훅 자동 발송' },
  { k: 'snapshot-age', icon: '⏳', label: '스냅샷 나이 감시', desc: '생성일 기준 오래된 스냅샷 탐지 · 나이/크기 필터 · CSV' },
  { k: 'zombie-vms', icon: '🧟', label: '좀비/방치 리소스', desc: '고아·접근불가 VM · 장기 정지 VM · 템플릿 · 스냅샷 대식가 — 회수 가능 용량(RVTools 스타일)' },
  { k: 'cert-expiry', icon: '📜', label: '인증서 만료 감시', desc: 'vCenter·NSX TLS 인증서 만료일 — D-90 경고 · D-30 위험 · 12시간 자동 프로브' },
  { k: 'rightsizing', icon: '📐', label: 'VM 라이트사이징', desc: '관측 평균/피크 기반 과대할당 VM 축소 추천 · 회수 가능 vCPU/RAM' },
  { k: 'capacity-forecast', icon: '📉', label: '용량 고갈 예측', desc: '데이터스토어 증가 추세 선형회귀 → 가득 찰 예상일(ETA) · 30일 임박 경고' },
  { k: 'alert-channels', icon: '📣', label: '알림 채널·이력', desc: 'Slack/Teams/웹훅 채널 상태 · 발화 중/최근 알림 이력 · 중복 억제 · 테스트 발송' },
  { k: 'compliance-report', icon: '📑', label: '버전/패치 준수', desc: 'VMware Tools 업그레이드 필요 · VM 하드웨어 버전 · ESXi 지원 종료(EOL) 분포' },
  { k: 'change-history', icon: '🕘', label: '구성 변경 이력', desc: '누가 언제 무엇을 바꿨나 — vCenter 이벤트 기반 변경 타임라인 · 분류/계정/대상 필터' },
  { k: 'unprotected-vms', icon: '🛟', label: '미보호 VM (백업 공백)', desc: '백업 소프트웨어의 스냅샷 이벤트가 관측되지 않은 가동 VM — 계정 패턴·기간 설정' },
  { k: 'solutions', icon: '🧱', label: 'VMware 솔루션 / NSX', desc: 'vCenter별 설치 버전' },
  { k: 'licenses', icon: '🔑', label: '라이선스 한눈에', desc: '제품별 할당/사용/만료' },
  { k: 'license-expiry', icon: '📅', label: '라이선스 만료일 확인', desc: 'ESXi·vCenter·vSAN·VCF/VVF·NSX·Horizon 등 수집 가능한 전 라이선스의 유효/만료 날짜 — 만료·90일 임박 강조, Horizon 연결 서버 등록, CSV' },
  { k: 'esxi', icon: '🖳', label: 'ESXi 버전별', desc: '호스트 ESXi 버전 분포/목록' },
  { k: 'vcversion', icon: '🏛️', label: 'vCenter 버전별', desc: 'vCenter 버전 분포' },
  { k: 'nsx', icon: '🛡️', label: 'NSX 관리', desc: '게이트웨이·세그먼트·노드·DFW 방화벽·보안그룹 등 NSX 전체 관리', perm: 'inv.nsx' },
  { k: 'hardware', icon: '🏷️', label: '벤더/모델 서머리', desc: '법인별 호스트 벤더·모델 수량' },
  { k: 'powermap', icon: '⚡', label: '전력 분석 (법인/모델별)', desc: '측정된 모든 서버 소비전력을 법인(vCenter)·모델·지역별로 분해 · 미매핑 포함 · CSV' },
  { k: 'hba', icon: '🔌', label: 'HBA 카드 속도', desc: '호스트 FC/iSCSI 어댑터 속도' },
  { k: 'gpu', icon: '🎮', label: 'GPU 인벤토리', desc: '호스트/모델별 GPU + 사용률 최근 5년 추이' },
  { k: 'serveranalysis', icon: '🔬', label: '서버 분석', desc: 'iDRAC 수집 하드웨어 분석 · GPU 찾기(모델별 장수)' },
  { k: 'fleet', icon: '🗂️', label: '통합 서버 인벤토리', desc: 'iDRAC 태그 + vCenter 조합 → 가상화 호스트 / 베어메탈 자동 분류 · 베어메탈 전력 합계 · 수동 예외 · CSV' },
  { k: 'nic-speed', icon: '🔌', label: '서버 NIC 속도 구분', desc: 'iDRAC 수집 서버의 물리 NIC 속도(10G/25G/100G…)별 분류 — DataCenter·가상화/베어메탈 필터 + CSV' },
  { k: 'nic-models', icon: '🧬', label: '서버 NIC 모델 확인', desc: 'iDRAC 수집 서버에 설치된 NIC 어댑터 종류·모델명(Intel/Broadcom/Mellanox…)별 분류 — DataCenter·가상화/베어메탈 필터 + CSV' },
  { k: 'topo3d', icon: '🌐', label: '구성도 (3D)', desc: '설정된 구성을 3D 네트워크로 — 줌인/아웃·회전·VM 펼치기' },
  { k: 'davinci-svc', icon: '🩺', label: '다빈치 서비스 점검', desc: '포탈 내부 서비스/수집기(vCenter·NSX·전력·지표·GPU·알림·백업·에이전트) 상태 한눈에' },
  { k: 'capacity-advisor', icon: '📊', label: '리소스 적정성 진단', desc: '포탈 서버(중앙+엣지)의 CPU·메모리·네트워크·디스크 상시 실측 — 1일/1주/1달 추이로 인프라 증설/감축 조언 (관리자)', adminOnly: true },
  { k: 'svcmon-config', icon: '⚙️', label: 'Monitoring 설정', desc: 'Monitoring 대상·점검 항목을 CSV 로 가져오기/내보내기 (샘플 제공) · 대량 자동등록 · 점검 템플릿' },
  { k: 'net-check', icon: '📡', label: '글로벌 네트워크 점검', desc: '전세계 vCenter·NSX 제어플레인 도달성·RTT + 네트워크 객체 요약' },
  { k: 'net-traffic', icon: '🔬', label: '네트워크 트래픽 분석', desc: '두 서버 간 tcpdump 캡처·분석(핸드셰이크·재전송·RST) + 로그 자체 장애 탐지' },
  { k: 'vmware-backup', icon: '🗃️', label: 'VMware 구성 백업', desc: '사이트의 수집 구성(호스트·VM·DS·네트워크·NSX) 스냅샷 내보내기' },
  { k: 'portaldb', icon: '🗄️', label: '포탈 DB', desc: '사용 중 모든 DB/데이터 파일의 경로·파일명·용도·크기·증가 추이' },
  { k: 'diskadd', icon: '🧩', label: '디스크 추가 자동화', desc: 'VM 디스크 추가 할당 자동화 (준비 중)', disabled: true, comingSoon: true },
  { k: 'backup', icon: '💾', label: '백업', desc: '설정 백업/복원 (준비 중)', disabled: true, comingSoon: true },
  { k: 'massdeploy', icon: '🚀', label: '대용량 배포', desc: '대량 배포 (준비 중)', disabled: true, comingSoon: true },
  { k: 'shutdown', icon: '🛑', label: '긴급중단', desc: '온도 상승·재난·PM 등 긴급 시 법인 전 장비 shutdown — 2인 이상 관리자 동의 필요', danger: true },
  { k: 'vmprovision', icon: '🆕', label: 'VM 생성', desc: '템플릿/사양 지정으로 신규 VM 생성 (관리자)', adminOnly: true },
  { k: 'agent-scans', icon: '🛰️', label: '에이전트 작업', desc: '에이전트별 IP 대역+iDRAC 계정 할당 → 각 에이전트가 로컬 스캔·자동등록·보고 (관리자)', adminOnly: true },
  { k: 'login-fails', icon: '🔐', label: '로그인 실패 분석', desc: 'vCenter/포탈 로그인 실패 이벤트 원인·추이 분석 (관리자)', adminOnly: true },
  { k: 'net-issues', icon: '🩺', label: '네트워크 이슈 분석', desc: '로그·캡처 기반 네트워크 장애 징후(재전송·RST·핸드셰이크) 분석 (관리자)', adminOnly: true },
];
