/**
 * loganalysis/catalog.js — 코어 규칙(rules.js) 외에 **코드 전수 스캔으로 추출한** 규칙(v2.583).
 *
 * 출처: v2.583 감사 워크플로의 카탈로그 에이전트 2개(수집 경로 · 엣지/인증/업그레이드 경로)가 console 출력 지점을
 * 훑어 만든 120개 중, 변환 스크립트가 ① 정규식 컴파일 ② 표본의 태그 == 규칙 태그 ③ 표본이 정규식에 맞음
 * ④ 대상 캡처가 비지 않음 ⑤ 소스 파일에 고정 조각(probe)이 실재 — 다섯을 통과한 118개다(중복 id 2개 제외).
 * 테스트(logAnalysis2583)가 ③·⑤ 를 매번 다시 확인한다 — 문구가 바뀌어 규칙이 조용히 죽지 않게.
 *
 * 필드: `re` 는 문자열(normalizeRules 가 컴파일) · `entity` 는 캡처 그룹 번호 · `entityLabel` 은 그 캡처가 무엇인지 ·
 *   `early` 는 **코어 규칙보다 먼저** 볼 규칙(GPU 게스트 VM별 실패 분류 — 코어 gpu-guest-fail-other 가 모든 ✗ 줄을
 *   먼저 잡아 세부 분류 13개가 한 번도 맞지 않던 것을 카탈로그 에이전트가 시뮬레이션으로 확인했다) ·
 *   `edge` 는 엣지 포탈 로그에서 찍히는 문장(중앙 로그에는 없다).
 * 표본의 이름·주소는 전부 합성값이다(공개 저장소 — v2.513 규약).
 */
const C = (o) => ({ category: "other", link: "", linkLabel: "", entity: 0, entityLabel: "", ...o });

export const CATALOG_RULES = [
  C({ id: "gpu-guest-guest-login", tag: "gpu-guest", severity: "high", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*(?:게스트 로그인 실패|InvalidGuestLogin|Failed to authenticate with the guest)",
    src: "server/src/gpu/guestops.js", probe: "InvalidGuestLogin",
    sample: "[gpu-guest]   ✗ gpu-vm-01: 게스트작업: StartProgramInGuest SOAP 실패: 게스트 로그인 실패 — 계정/비밀번호 확인 | raw: SOAP 500: Failed to authenticate with the guest operating system using the supplied credentials. / SSH: SSH 수집 실패: SSH 연결 거부(sshd 미동작/포트 차단)",
    title: "게스트 작업(VMware Tools)으로 nvidia-smi 를 실행하려 했으나 게스트 OS 가 계정·비밀번호를 거부했습니다",
    meaning: "게스트 작업(VMware Tools)으로 nvidia-smi 를 실행하려 했으나 게스트 OS 가 계정·비밀번호를 거부했습니다. auto 방식에서는 같은 줄 뒤에 SSH 폴백 사유가 붙지만 근본 원인은 이 게스트 로그인 실패입니다. 매 주기 반복되면 게스트 계정 잠금 정책에 걸릴 수 있습니다.",
    action: "GPU 게스트 수집 설정에서 이 VM(또는 법인 기본값)의 게스트 계정·비밀번호를 고치고, GPU 수집 진단의 VM별 결과로 다음 주기 성공을 확인하세요. 수집이 필요 없는 VM 이면 대상에서 빼세요.",
    link: "#/settings/gpu-guest", linkLabel: "GPU 게스트 수집" }),
  C({ id: "gpu-guest-tools-unavailable", tag: "gpu-guest", severity: "medium", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*(?:VMware Tools 미실행/구버전|[Gg]uest operations agent)",
    src: "server/src/gpu/guestops.js", probe: "VMware Tools 미실행/구버전 — 게스트 작업 불가",
    sample: "[gpu-guest]   ✗ gpu-vm-02: 게스트작업: StartProgramInGuest SOAP 실패: VMware Tools 미실행/구버전 — 게스트 작업 불가 | raw: SOAP 500: VMware Tools is not running in the virtual machine. / SSH: SSH 수집 실패: SSH 타임아웃(IP 미도달/방화벽)",
    title: "그 VM 의 VMware Tools 가 꺼져 있거나 게스트 작업을 지원하지 않는 버전이라 게스트 작업 경로가 막혔습니다",
    meaning: "그 VM 의 VMware Tools 가 꺼져 있거나 게스트 작업을 지원하지 않는 버전이라 게스트 작업 경로가 막혔습니다. 뒤에 붙은 SSH 사유는 폴백 결과일 뿐입니다.",
    action: "vCenter 에서 해당 VM 의 VMware Tools 상태(실행·버전)를 확인해 설치·업그레이드하세요. Linux VM 이고 sshd 가 있으면 GPU 게스트 수집의 수집 방식을 SSH 로 바꿀 수 있습니다.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-vm-powered-off", tag: "gpu-guest", severity: "low", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*VM 전원 꺼짐",
    src: "server/src/gpu/guestops.js", probe: "VM 전원 꺼짐",
    sample: "[gpu-guest]   ✗ gpu-vm-03: StartProgramInGuest SOAP 실패: VM 전원 꺼짐 | raw: SOAP 500: The attempted operation cannot be performed in the current state (Powered off).",
    title: "수집 시점에 VM 이 꺼져 있어 게스트 작업을 실행할 수 없었습니다",
    meaning: "수집 시점에 VM 이 꺼져 있어 게스트 작업을 실행할 수 없었습니다. 선별 단계 이후 전원이 바뀐 경우이며 결함이 아닙니다.",
    action: "의도적으로 꺼 둔 VM 이면 조치할 것이 없습니다. 계속 반복되면 그 VM 을 GPU 게스트 수집 대상에서 빼세요.",
    link: "#/settings/gpu-guest", linkLabel: "GPU 게스트 수집" }),
  C({ id: "gpu-guest-guestop-timeout", tag: "gpu-guest", severity: "low", category: "network", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*게스트 작업 타임아웃",
    src: "server/src/gpu/guestops.js", probe: "게스트 작업 타임아웃",
    sample: "[gpu-guest]   ✗ gpu-vm-04: 게스트작업: StartProgramInGuest SOAP 실패: 게스트 작업 타임아웃 | raw: The operation was aborted due to timeout",
    title: "vCenter 게스트 작업 호출이 시한 안에 끝나지 않았습니다",
    meaning: "vCenter 게스트 작업 호출이 시한 안에 끝나지 않았습니다. 고지연 vCenter(RTT 800ms 초과 법인)나 게스트 부하가 높을 때 납니다.",
    action: "GPU 게스트 수집 설정의 타임아웃을 늘리거나 동시 수집 수를 줄이세요. 특정 법인에만 몰리면 그 vCenter 의 응답 지연을 먼저 확인하세요.",
    link: "#/settings/gpu-guest", linkLabel: "GPU 게스트 수집" }),
  C({ id: "gpu-guest-nvsmi-stderr", tag: "gpu-guest", severity: "medium", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*게스트 오류: ",
    src: "server/src/gpu/guestops.js", probe: "게스트 오류:",
    sample: "[gpu-guest]   ✗ gpu-vm-05: 게스트작업: 게스트 오류: /bin/sh: nvidia-smi: command not found / SSH: SSH 수집 실패: SSH 인증 실패(계정/비번 또는 비밀번호 로그인 비활성)",
    title: "게스트 작업으로 명령은 실행됐고 nvidia-smi 의 표준오류를 회수했습니다",
    meaning: "게스트 작업으로 명령은 실행됐고 nvidia-smi 의 표준오류를 회수했습니다. 표본의 문구(command not found · NVIDIA-SMI has failed 등)가 게스트 쪽 실제 원인입니다 — 대개 드라이버 미설치·PATH 누락입니다.",
    action: "표본의 게스트 오류 문구대로 그 VM 의 NVIDIA 드라이버·nvidia-smi 경로를 확인하세요(Windows 는 nvidia-smi.exe 가 PATH 에 있어야 합니다). 포탈 설정으로 고칠 수 있는 문제가 아닙니다.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-retrieve-404", tag: "gpu-guest", severity: "medium", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*회수 실패\\(\\.out/\\.err 모두 HTTP404",
    src: "server/src/gpu/guestops.js", probe: "err 모두 HTTP404",
    sample: "[gpu-guest]   ✗ gpu-vm-06: 회수 실패(.out/.err 모두 HTTP404 — 파일 비었거나 ESXi가 티켓 거부) · stdout: 파일 다운로드 실패(size=0B): 10.0.0.21(원본)=HTTP404",
    title: "명령은 실행됐지만 결과 파일(.out/.err)을 ESXi 에서 내려받지 못했습니다(모두 HTTP 404). size=0B 면 nvidia-smi 가 아무것도 출력하지 않은 것이고, 그 외에는 ESXi 가 전송 티켓을 거부한 것입니다",
    meaning: "명령은 실행됐지만 결과 파일(.out/.err)을 ESXi 에서 내려받지 못했습니다(모두 HTTP 404). size=0B 면 nvidia-smi 가 아무것도 출력하지 않은 것이고, 그 외에는 ESXi 가 전송 티켓을 거부한 것입니다.",
    action: "size=0B 이면 그 VM 에서 nvidia-smi 를 직접 실행해 출력이 나오는지 확인하세요. 크기가 있는데도 404 면 GPU 수집 진단의 다운로드 후보(ESXi 관리 IP·FQDN)가 VM 이 올라간 호스트를 가리키는지 확인하세요.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-download-unreachable", tag: "gpu-guest", severity: "medium", category: "network", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*파일 다운로드 실패\\(size=",
    src: "server/src/gpu/guestops.js", probe: "파일 다운로드 실패",
    sample: "[gpu-guest]   ✗ gpu-vm-07: 게스트작업: 파일 다운로드 실패(size=512B): 10.0.0.21(원본)=The operation was aborted due to timeout | 10.0.0.5=fetch failed / SSH: SSH 수집 실패: SSH 타임아웃(IP 미도달/방화벽)",
    title: "게스트에서 nvidia-smi 는 실행됐지만 결과 파일을 ESXi 호스트에서 내려받는 HTTPS 요청이 응답 없이 실패했습니다(시한 초과·연결 실패). 이 포탈(수집 노드)에서 그 VM 이 올라간 ESXi 관리 IP 의 443 포트로 닿지 않는 구성입니다",
    meaning: "게스트에서 nvidia-smi 는 실행됐지만 결과 파일을 ESXi 호스트에서 내려받는 HTTPS 요청이 응답 없이 실패했습니다(시한 초과·연결 실패). 이 포탈(수집 노드)에서 그 VM 이 올라간 ESXi 관리 IP 의 443 포트로 닿지 않는 구성입니다.",
    action: "수집 노드에서 ESXi 관리 IP 443 으로의 방화벽을 여세요. 열 수 없으면 Linux VM 은 수집 방식을 SSH 로 바꾸세요. 법인 전체가 이 사유면 그 법인을 엣지(수집 서버) 위임으로 돌리는 것이 근본 해결입니다.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-nvsmi-empty", tag: "gpu-guest", severity: "low", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*nvidia-smi (?:출력이 비어 있음|출력 없음|결과 없음)",
    src: "server/src/gpu/guestops.js", probe: "nvidia-smi",
    sample: "[gpu-guest]   ✗ gpu-vm-09: nvidia-smi 출력이 비어 있음(명령은 실행됐으나 stdout 없음)",
    title: "명령은 실행됐지만 nvidia-smi 가 GPU 값을 한 줄도 내지 않았습니다",
    meaning: "명령은 실행됐지만 nvidia-smi 가 GPU 값을 한 줄도 내지 않았습니다. 드라이버가 GPU 를 인식하지 못했거나 nvidia-smi 가 없는 VM 입니다.",
    action: "그 VM 에서 nvidia-smi 를 직접 실행해 GPU 가 보이는지 확인하세요. GPU 가 없는 VM 이 대상에 잡혔다면 GPU 게스트 수집 대상에서 빼세요.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-nvsmi-parse", tag: "gpu-guest", severity: "low", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*nvidia-smi 출력 파싱 실패: ",
    src: "server/src/gpu/sshCollect.js", probe: "nvidia-smi 출력 파싱 실패:",
    sample: "[gpu-guest]   ✗ gpu-vm-10: SSH 수집 실패: nvidia-smi 출력 파싱 실패: No devices were found",
    title: "SSH 로 nvidia-smi 를 실행했으나 출력이 예상한 CSV 형식이 아니었습니다",
    meaning: "SSH 로 nvidia-smi 를 실행했으나 출력이 예상한 CSV 형식이 아니었습니다. 표본에 출력 앞부분이 함께 찍힙니다(No devices were found 등).",
    action: "표본의 출력 문구를 보고 그 VM 의 GPU·드라이버 상태를 확인하세요. 정상 출력인데 파싱이 실패하면 드라이버 버전과 표본을 개발자에게 전달하세요.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-no-guest-ip", tag: "gpu-guest", severity: "low", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*게스트 IP 없음\\(VMware Tools가 IP 미보고\\)",
    src: "server/src/gpu/sshCollect.js", probe: "VMware Tools가 IP 미보고",
    sample: "[gpu-guest]   ✗ gpu-vm-11: 게스트 IP 없음(VMware Tools가 IP 미보고) — SSH 수집 불가",
    title: "SSH 방식은 게스트 IP 가 필요한데 VMware Tools 가 IP 를 보고하지 않아 접속 대상이 없습니다",
    meaning: "SSH 방식은 게스트 IP 가 필요한데 VMware Tools 가 IP 를 보고하지 않아 접속 대상이 없습니다.",
    action: "VM 의 VMware Tools 상태를 확인하거나, GPU 게스트 수집 설정에서 그 VM 의 접속 IP 를 직접 지정하세요.",
    link: "#/settings/gpu-guest", linkLabel: "GPU 게스트 수집" }),
  C({ id: "gpu-guest-ssh-unreachable", tag: "gpu-guest", severity: "low", category: "network", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*SSH 경로 없음\\(망 분리\\)",
    src: "server/src/gpu/sshCollect.js", probe: "SSH 경로 없음",
    sample: "[gpu-guest]   ✗ gpu-vm-12: SSH 수집 실패: SSH 경로 없음(망 분리)",
    title: "수집 노드에서 게스트 IP 로 가는 라우팅 자체가 없습니다(EHOSTUNREACH/ENETUNREACH). 방화벽 시한 초과와 달리 경로가 없다는 뜻입니다",
    meaning: "수집 노드에서 게스트 IP 로 가는 라우팅 자체가 없습니다(EHOSTUNREACH/ENETUNREACH). 방화벽 시한 초과와 달리 경로가 없다는 뜻입니다.",
    action: "수집 방식을 게스트 작업(VMware Tools)으로 바꾸거나, 그 법인을 엣지 위임으로 돌려 게스트 망 안에서 수집하세요.",
    link: "#/settings/gpu-guest", linkLabel: "GPU 게스트 수집" }),
  C({ id: "gpu-guest-ssh-deadline", tag: "gpu-guest", severity: "low", category: "network", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*SSH 수집 시간 초과\\((\\d+)초\\)",
    src: "server/src/gpu/sshCollect.js", probe: "SSH 수집 시간 초과",
    sample: "[gpu-guest]   ✗ gpu-vm-14: SSH 수집 실패: SSH 수집 시간 초과(40초)",
    title: "SSH 접속은 됐거나 진행 중이었지만 IP 한 곳당 예산(핸드셰이크 + nvidia-smi, 시한의 2배) 안에 끝나지 않아 세션을 끊었습니다",
    meaning: "SSH 접속은 됐거나 진행 중이었지만 IP 한 곳당 예산(핸드셰이크 + nvidia-smi, 시한의 2배) 안에 끝나지 않아 세션을 끊었습니다. nvidia-smi 가 멈춰 있거나(드라이버 이상) 게스트 부하가 높은 경우입니다. 핸드셰이크 단계의 시한 초과(SSH 타임아웃)와는 다른 사유입니다.",
    action: "그 VM 에서 nvidia-smi 가 즉시 끝나는지 직접 확인하세요. 멈춘다면 게스트의 NVIDIA 드라이버 문제입니다. 고지연 법인이면 GPU 게스트 수집 설정의 타임아웃을 늘리세요.",
    link: "#/settings/gpu-guest", linkLabel: "GPU 게스트 수집" }),
  C({ id: "gpu-guest-guestops-manager", tag: "gpu-guest", severity: "medium", category: "stability", entity: 1, entityLabel: "VM 이름", early: true,
    re: "✗ (.+?): .*GuestOperationsManager 사용 불가",
    src: "server/src/gpu/guestops.js", probe: "GuestOperationsManager 사용 불가",
    sample: "[gpu-guest]   ✗ gpu-vm-13: 게스트작업: GuestOperationsManager 사용 불가 / SSH: SSH 수집 실패: SSH 연결 거부(sshd 미동작/포트 차단)",
    title: "vCenter 가 게스트 작업 관리자(processManager·fileManager)를 돌려주지 않았습니다",
    meaning: "vCenter 가 게스트 작업 관리자(processManager·fileManager)를 돌려주지 않았습니다. 수집 계정 권한에 게스트 작업이 없거나 vCenter 가 그 기능을 막은 경우입니다.",
    action: "vCenter 수집 계정 역할에 Virtual machine > Guest operations 권한이 있는지 확인하세요. 같은 vCenter 의 모든 VM 에서 반복되면 권한 문제가 확실합니다.",
    link: "#/settings/vcenter-admin", linkLabel: "vCenter 등록·관리" }),
  C({ id: "gpu-guest-download-neterr", tag: "gpu-guest", severity: "low", category: "network", entity: 1, entityLabel: "다운로드 후보 호스트",
    re: "\\[[^\\]]+\\] 다운로드 (\\S+?)(?:\\(원본\\))? → (?!HTTP \\d)",
    src: "server/src/gpu/guestops.js", probe: "] 다운로드",
    sample: "[gpu-guest]     [vm-1234] 다운로드 10.0.0.21(원본) → The operation was aborted due to timeout",
    title: "결과 파일 다운로드 후보 호스트에 HTTP 응답조차 받지 못했습니다(시한 초과·연결 거부). 같은 호스트가 반복되면 이 수집 노드에서 그 ESXi 의 443 포트에 닿지 않습니다",
    meaning: "결과 파일 다운로드 후보 호스트에 HTTP 응답조차 받지 못했습니다(시한 초과·연결 거부). 같은 호스트가 반복되면 이 수집 노드에서 그 ESXi 의 443 포트에 닿지 않습니다.",
    action: "반복되는 호스트(엔티티)를 확인해 수집 노드 → ESXi 관리 IP 443 방화벽을 여세요.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-vc-collect-fail", tag: "gpu-guest", severity: "medium", category: "stability", entity: 1, entityLabel: "vCenter id",
    re: "(?<!✗.*)(\\S+) 수집 실패: ",
    src: "server/src/gpu/poller.js", probe: "수집 실패:",
    sample: "[gpu-guest] vc-a 수집 실패: Cannot read properties of undefined (reading 'hosts')",
    title: "그 vCenter 의 GPU 게스트 수집 한 주기가 VM 별 처리 밖에서 예외로 끝났습니다",
    meaning: "그 vCenter 의 GPU 게스트 수집 한 주기가 VM 별 처리 밖에서 예외로 끝났습니다. 그 vCenter 의 GPU VM 전부가 이번 주기에 빠졌습니다.",
    action: "GPU 수집 진단에서 그 vCenter 의 단계가 예외로 끝났는지 확인하세요. 매 주기 반복되면 예외 문구를 개발자에게 전달하세요.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "collect-vc-auth", tag: "collect", severity: "high", category: "auth", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: .* — 인증 실패 — 계정/비밀번호",
    src: "server/src/store.js", probe: ") 연결 실패:",
    sample: "[collect] vc-a (VC-SEOUL) 연결 실패: Cannot complete login due to an incorrect user name or password. — 인증 실패 — 계정/비밀번호 또는 권한을 확인하세요.",
    title: "vCenter 가 수집 계정의 로그인을 거부했습니다",
    meaning: "vCenter 가 수집 계정의 로그인을 거부했습니다. 그 vCenter 는 마지막 정상 데이터로 이월되지만 새 값이 들어오지 않고, 매 주기 로그인 시도가 반복돼 계정 잠금 정책에 걸릴 수 있습니다.",
    action: "vCenter 등록에서 그 vCenter 의 수집 계정·비밀번호를 고치고 vCenter 연결 테스트로 확인하세요. 비밀번호를 바꾼 직후라면 SSO 계정 잠금 여부도 확인하세요.",
    link: "#/settings/vcenter-admin", linkLabel: "vCenter 등록·관리" }),
  C({ id: "collect-vc-dns", tag: "collect", severity: "high", category: "network", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: .* — DNS 조회 실패",
    src: "server/src/store.js", probe: ") 연결 실패:",
    sample: "[collect] vc-b (VC-EAST) 연결 실패: fetch failed: getaddrinfo ENOTFOUND vc-b.example.local — DNS 조회 실패 — 호스트명/주소를 확인하세요 (DNS 또는 hosts).",
    title: "이 포탈이 vCenter 호스트명을 IP 로 바꾸지 못했습니다",
    meaning: "이 포탈이 vCenter 호스트명을 IP 로 바꾸지 못했습니다. 네트워크가 아니라 이름 해석 문제입니다.",
    action: "vCenter 등록의 주소 오기재를 확인하고, 포탈 서버의 DNS 설정(/etc/resolv.conf) 또는 /etc/hosts 에 그 이름이 있는지 확인하세요.",
    link: "#/settings/vcenter-admin", linkLabel: "vCenter 등록·관리" }),
  C({ id: "collect-vc-refused", tag: "collect", severity: "high", category: "network", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: .* — 연결 거부 — ",
    src: "server/src/store.js", probe: ") 연결 실패:",
    sample: "[collect] vc-c (VC-WEST) 연결 실패: fetch failed: connect ECONNREFUSED 10.0.0.10:443 — 연결 거부 — 포트(443)·vCenter 서비스·방화벽을 확인하세요.",
    title: "vCenter 주소에는 닿았지만 443 포트가 연결을 거부했습니다",
    meaning: "vCenter 주소에는 닿았지만 443 포트가 연결을 거부했습니다. vCenter 서비스 중지·재부팅 중이거나 중계(HAProxy) 포트가 내려간 상태입니다.",
    action: "vCenter 의 서비스 상태(VAMI)와 중계 서버를 거친다면 그 포워딩 포트를 확인하세요. vCenter 연결 테스트로 즉시 재확인할 수 있습니다.",
    link: "#/settings/vcenter-test", linkLabel: "vCenter 연결 테스트" }),
  C({ id: "collect-vc-timeout", tag: "collect", severity: "medium", category: "network", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: .* — 연결 시간 초과",
    src: "server/src/store.js", probe: ") 연결 실패:",
    sample: "[collect] vc-d (VC-EU2) 연결 실패: fetch failed: Connect Timeout Error (attempted address: 10.0.0.12:443, timeout: 10000ms) — 연결 시간 초과 — telnet(TCP)은 되는데 여기서 막히면 중계(HAProxy) reload·방화벽 idle로 keep-alive 연결이 끊긴 경우가 많습니다(다음 주기에 새 연결로 자동 복구). 지속되면 네트워크 경로·중계 서버 상태를 확인하세요.",
    title: "vCenter 수집이 시한 안에 끝나지 않았습니다",
    meaning: "vCenter 수집이 시한 안에 끝나지 않았습니다. 한두 번은 중계 reload·keep-alive 끊김으로 다음 주기에 자동 복구되지만, 고지연 법인(RTT 800ms 초과)에서 연속되면 그 vCenter 데이터가 낡습니다.",
    action: "같은 vCenter 가 연속으로 찍히는지 보세요. 연속이면 통신 점검으로 경로 단계를 확인하고, 고지연 법인은 엣지 위임을 검토하세요.",
    link: "#/tools/link-check", linkLabel: "통신 점검" }),
  C({ id: "collect-vc-cert", tag: "collect", severity: "high", category: "network", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: .* — 인증서 오류",
    src: "server/src/store.js", probe: ") 연결 실패:",
    sample: "[collect] vc-e (VC-LAB) 연결 실패: fetch failed: self-signed certificate — 인증서 오류 — vCenter 자체서명이면 VC_TLS_REJECT_UNAUTHORIZED=false, 중앙↔엣지(수집 서버) 자체서명 HTTPS면 WAN_TLS_INSECURE=true 로 두세요(가능하면 사설 CA 신뢰가 우선).",
    title: "TLS 인증서 검증에 실패해 연결 자체를 하지 않았습니다",
    meaning: "TLS 인증서 검증에 실패해 연결 자체를 하지 않았습니다. vCenter 인증서가 바뀌었거나(갱신·재발급) 자체서명입니다.",
    action: "vCenter 인증서를 사설 CA 로 신뢰시키는 것이 우선입니다. 불가하면 portal.env 의 VC_TLS_REJECT_UNAUTHORIZED 를 검토하세요(보안 트레이드오프). 인증서 만료 점검 도구로 만료 여부도 확인하세요.",
    link: "#/tools/cert-expiry", linkLabel: "인증서 만료 감시" }),
  C({ id: "collect-vc-network", tag: "collect", severity: "medium", category: "network", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: .* — (?:연결이 재설정됨|호스트/네트워크에 도달할 수 없음)",
    src: "server/src/store.js", probe: ") 연결 실패:",
    sample: "[collect] vc-f (VC-EU) 연결 실패: fetch failed: connect EHOSTUNREACH 10.0.0.11:443 — 호스트/네트워크에 도달할 수 없음 — 라우팅/방화벽을 확인하세요.",
    title: "vCenter 까지의 네트워크 경로가 없거나(EHOSTUNREACH) 연결이 도중에 끊겼습니다(ECONNRESET).",
    meaning: "vCenter 까지의 네트워크 경로가 없거나(EHOSTUNREACH) 연결이 도중에 끊겼습니다(ECONNRESET).",
    action: "통신 점검에서 그 vCenter 링크의 도달 단계(DNS → TCP → TLS)를 확인하고, 중계·방화벽 경로를 점검하세요.",
    link: "#/tools/link-check", linkLabel: "통신 점검" }),
  C({ id: "collect-vc-deadline", tag: "collect", severity: "medium", category: "network", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: vCenter 수집 데드라인 초과\\((\\d+)초\\)",
    src: "server/src/store.js", probe: "vCenter 수집 데드라인 초과(",
    sample: "[collect] vc-d (VC-EU3) 연결 실패: vCenter 수집 데드라인 초과(90초) — 응답이 느립니다",
    title: "한 vCenter 수집(로그인부터 로그아웃까지 전체)이 데드라인 안에 끝나지 않아 실패로 끊었습니다",
    meaning: "한 vCenter 수집(로그인부터 로그아웃까지 전체)이 데드라인 안에 끝나지 않아 실패로 끊었습니다. 다른 vCenter 게시를 막지 않기 위한 장치이며, 그 vCenter 는 마지막 정상 데이터로 이월됩니다. 이 문구에는 원인 힌트가 붙지 않습니다.",
    action: "고지연 법인에서 반복되면 vCenter 등록의 건별 타임아웃(데드라인은 그 3배, 최소 90초)을 늘리거나 엣지 위임을 검토하세요. 특정 시각에만 몰리면 그 시각의 vCenter 부하를 확인하세요.",
    link: "#/settings/vcenter-admin", linkLabel: "vCenter 등록·관리" }),
  C({ id: "collect-vc-fail", tag: "collect", severity: "medium", category: "stability", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 연결 실패: ",
    src: "server/src/store.js", probe: ") 연결 실패:",
    sample: "[collect] vc-g (VC-LAB2) 연결 실패: SOAP fault: ServerFaultCode",
    title: "vCenter 인벤토리 수집이 위 분류(인증·DNS·거부·시한·인증서·경로)에 들지 않는 사유로 실패했습니다",
    meaning: "vCenter 인벤토리 수집이 위 분류(인증·DNS·거부·시한·인증서·경로)에 들지 않는 사유로 실패했습니다. 마지막 정상 데이터로 이월되며 새 값은 들어오지 않습니다.",
    action: "vCenter 연결 테스트로 같은 오류가 재현되는지 보고, 표본의 원문을 확인하세요. 반복되면 원문을 개발자에게 전달하세요.",
    link: "#/settings/vcenter-test", linkLabel: "vCenter 연결 테스트" }),
  C({ id: "collect-soap-rest-fallback", tag: "collect", severity: "medium", category: "config", entity: 1, entityLabel: "vCenter id",
    re: "SOAP metrics failed for (\\S+) \\(.*\\); falling back to REST list API",
    src: "server/src/vcenter/restClient.js", probe: "; falling back to REST list API",
    sample: "[collect] SOAP metrics failed for vc-h (unexpected SOAP response); falling back to REST list API",
    title: "SOAP 수집이 형식 오류·미지원으로 실패해 REST 목록 API 로 대체했습니다",
    meaning: "SOAP 수집이 형식 오류·미지원으로 실패해 REST 목록 API 로 대체했습니다. 대체 경로는 사용률·전력·GPU 같은 지표가 비어 있는 저품질 데이터입니다.",
    action: "그 vCenter 의 버전·수집 계정 권한을 vCenter 연결 테스트로 확인하세요. 계속 반복되면 표본 원문을 개발자에게 전달하세요.",
    link: "#/settings/vcenter-test", linkLabel: "vCenter 연결 테스트" }),
  C({ id: "collect-vgpu-counter-missing", tag: "collect", severity: "low", category: "config", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) gpu\\.utilization 카운터 없음",
    src: "server/src/vcenter/soapClient.js", probe: "utilization 카운터 없음",
    sample: "[collect] vc-a gpu.utilization 카운터 없음 — vGPU 사용률 미수집(NVIDIA vGPU Manager VIB/드라이버 또는 vCenter 카운터 확인)",
    title: "GPU 호스트가 있는데 vCenter 에 gpu.utilization 성능 카운터가 없어 호스트 vGPU 사용률을 모으지 못합니다",
    meaning: "GPU 호스트가 있는데 vCenter 에 gpu.utilization 성능 카운터가 없어 호스트 vGPU 사용률을 모으지 못합니다.",
    action: "ESXi 에 NVIDIA vGPU Manager VIB 가 설치돼 있는지 확인하세요. 설치가 어려우면 GPU 게스트 수집(게스트 nvidia-smi)으로 대체하세요.",
    link: "#/settings/gpu-guest", linkLabel: "GPU 게스트 수집" }),
  C({ id: "store-refresh-fail", tag: "store", severity: "high", category: "stability",
    re: "refresh failed: ",
    src: "server/src/store.js", probe: "refresh failed:",
    sample: "[store] refresh failed: Cannot read properties of undefined (reading \"map\")",
    title: "인벤토리 스냅샷 갱신 주기 전체가 예외로 끝났습니다",
    meaning: "인벤토리 스냅샷 갱신 주기 전체가 예외로 끝났습니다. 모든 화면이 직전 스냅샷에 머물러 있습니다.",
    action: "표본의 예외 문구를 개발자에게 전달하세요. 반복되면 진단·로그에서 직전 변경(업그레이드·설정)과 시각을 대조하세요.",
    link: "#/settings/diagnostics", linkLabel: "진단·로그" }),
  C({ id: "vmseries-disk-low", tag: "vmseries", severity: "high", category: "data",
    re: "디스크 여유 ([\\d.]+)GB < (\\d+)GB — 이번 주기 저장 건너뜀",
    src: "server/src/vmseries/poller.js", probe: "GB — 이번 주기 저장 건너뜀",
    sample: "[vmseries] 디스크 여유 3.2GB < 10GB — 이번 주기 저장 건너뜀(구간 소실)",
    title: "포탈 디스크 여유가 하한보다",
    meaning: "포탈 디스크 여유가 하한보다 적어 이번 주기의 20초 스파이크 수집·저장을 통째로 건너뛰었습니다. ESXi 버퍼(60분)를 넘기면 그 구간은 영구히 소실됩니다.",
    action: "VM 실시간 스파이크 수집 설정에서 보존일을 줄이거나 대상 vCenter 를 좁히고, 포탈 데이터 디스크 여유를 확보하세요. 폴더 사용량 리포트로 무엇이 공간을 쓰는지 확인할 수 있습니다.",
    link: "#/settings/vmseries", linkLabel: "VM 실시간 스파이크 수집" }),
  C({ id: "vmseries-vc-auth", tag: "vmseries", severity: "high", category: "auth", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 수집 실패: .* — 인증 실패 — ",
    src: "server/src/vmseries/poller.js", probe: ") 수집 실패:",
    sample: "[vmseries] vc-a (VC-SEOUL) 수집 실패: Cannot complete login due to an incorrect user name or password. — 인증 실패 — 계정/비밀번호 또는 권한을 확인하세요.",
    title: "실시간 스파이크 수집이 그 vCenter 로그인에서 거부됐습니다",
    meaning: "실시간 스파이크 수집이 그 vCenter 로그인에서 거부됐습니다. 주기(최대 60분)당 한 번 실패하면 겹침 10분을 뺀 약 40분 구간이 영구 소실됩니다.",
    action: "vCenter 등록에서 수집 계정·비밀번호를 고치고 vCenter 연결 테스트로 확인하세요. 인벤토리 수집(collect)도 같은 계정이면 함께 실패하고 있을 것입니다.",
    link: "#/settings/vcenter-admin", linkLabel: "vCenter 등록·관리" }),
  C({ id: "vmseries-vc-fail", tag: "vmseries", severity: "medium", category: "stability", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) \\((.*?)\\) 수집 실패: ",
    src: "server/src/vmseries/poller.js", probe: ") 수집 실패:",
    sample: "[vmseries] vc-b (VC-EAST) 수집 실패: fetch failed: connect ECONNREFUSED 10.0.0.10:443 — 연결 거부 — 포트(443)·vCenter 서비스·방화벽을 확인하세요.",
    title: "그 vCenter 의 실시간 스파이크 수집이 실패했습니다",
    meaning: "그 vCenter 의 실시간 스파이크 수집이 실패했습니다. 한 주기 실패는 약 40분 구간의 영구 소실입니다(ESXi 버퍼 60분).",
    action: "표본 끝의 힌트(연결 거부·시한 초과·인증서)에 따라 vCenter 경로를 확인하세요. 고지연 법인이면 수집 주기를 줄여 겹침을 늘리는 것도 방법입니다.",
    link: "#/settings/vmseries", linkLabel: "VM 실시간 스파이크 수집" }),
  C({ id: "bmusage-os-auth-stop", tag: "bmusage", severity: "high", category: "auth", entity: 1, entityLabel: "서버 이름",
    re: "([^\\]\\s][^\\]]*?): 인증 실패로 주기 수집 정지\\((\\d+)회\\)",
    src: "server/src/bmusage/poller.js", probe: ": 인증 실패로 주기 수집 정지",
    sample: "[bmusage] bm-srv-01: 인증 실패로 주기 수집 정지(3회) — SSH 인증 실패: All configured authentication methods failed",
    title: "베어메탈 서버의 OS 계정이 거부돼 그 서버의 주기 수집을 멈췄습니다(계정 잠금 방지). 수동 실행은 막지 않으며, 등록부의 자격증명이 바뀌면 자동으로 재개됩니다",
    meaning: "베어메탈 서버의 OS 계정이 거부돼 그 서버의 주기 수집을 멈췄습니다(계정 잠금 방지). 수동 실행은 막지 않으며, 등록부의 자격증명이 바뀌면 자동으로 재개됩니다.",
    action: "베어메탈 스토리지 등록부에서 그 서버의 OS 계정·비밀번호를 고치세요. 저장하면 다음 주기부터 자동 재개됩니다.",
    link: "#/tools/bm-storage", linkLabel: "베어메탈 스토리지" }),
  C({ id: "bmusage-idrac-auth-stop", tag: "bmusage", severity: "high", category: "auth", entity: 1, entityLabel: "서버 이름",
    re: "([^\\]\\s][^\\]]*?): iDRAC 인증 실패로 대체 수집 정지\\((\\d+)회\\)",
    src: "server/src/bmusage/poller.js", probe: ": iDRAC 인증 실패로 대체 수집 정지",
    sample: "[bmusage] bm-srv-02: iDRAC 인증 실패로 대체 수집 정지(2회)",
    title: "Enterprise 라이선스 대체 경로(센서 GET·racadm SSH)에서 iDRAC 계정이 거부돼 그 경로를 멈췄습니다",
    meaning: "Enterprise 라이선스 대체 경로(센서 GET·racadm SSH)에서 iDRAC 계정이 거부돼 그 경로를 멈췄습니다. 잠기면 전력·온도 수집까지 죽으므로 반복 시도하지 않습니다.",
    action: "iDRAC 서버 등록에서 그 서버의 계정·비밀번호를 고치세요. 자격증명이 바뀌면 자동 재개됩니다.",
    link: "#/settings/idrac-admin", linkLabel: "iDRAC 서버 등록" }),
  C({ id: "bmusage-db-unavailable", tag: "bmusage-db", severity: "medium", category: "config",
    re: "사용 불가\\(DB 없이 동작\\): ",
    src: "server/src/bmusage/db.js", probe: "DB 없이 동작",
    sample: "[bmusage-db] 사용 불가(DB 없이 동작): SQLITE_CANTOPEN: unable to open database file",
    title: "베어메탈 사용률 DB 를 열지 못해 이력 없이 동작합니다",
    meaning: "베어메탈 사용률 DB 를 열지 못해 이력 없이 동작합니다. 추이·일 롤업이 쌓이지 않습니다.",
    action: "데이터 디렉터리 권한·여유 공간과 Node 의 node:sqlite 지원을 확인한 뒤 포탈을 재시작하세요.",
    link: "#/tools/bm-usage", linkLabel: "베어메탈 사용률" }),
  C({ id: "storage-push-413", tag: "storage-push", severity: "high", category: "data",
    re: "중앙이 본문 크기를 거부\\(413\\)\\. 장비 (\\d+)대",
    src: "server/src/storage/push.js", probe: "중앙이 본문 크기를 거부",
    sample: "[storage-push] 중앙이 본문 크기를 거부(413). 장비 24대 · JSON 2210KB — 중앙의 JSON_BODY_LIMIT 또는 수집 장비 수를 확인하세요.",
    title: "이 엣지의 스토리지 스냅샷 전량이 중앙에서 크기 초과로 거부됐습니다",
    meaning: "이 엣지의 스토리지 스냅샷 전량이 중앙에서 크기 초과로 거부됐습니다. 413 은 재시도되지 않으므로 그 법인의 스토리지 데이터가 중앙에 도착하지 않습니다.",
    action: "중앙 portal.env 의 JSON_BODY_LIMIT 을 늘리고 재시작하세요. 엣지 로그 화면에서 이 엣지의 스토리지 push 상태가 성공으로 바뀌는지 확인하세요.",
    link: "#/tools/edge-log", linkLabel: "엣지 로그 · 진행상태" }),
  C({ id: "storage-mock-mode", tag: "storage", severity: "high", category: "config",
    re: "(?:⚠\\s*)?DATA_SOURCE=mock — 스토리지 수집이 가짜 데이터를 만듭니다",
    src: "server/src/storage/poller.js", probe: "DATA_SOURCE=mock — 스토리지 수집이 가짜 데이터를 만듭니다",
    sample: "[storage] ⚠ DATA_SOURCE=mock — 스토리지 수집이 가짜 데이터를 만듭니다. 실제 장비를 수집하려면 portal.env 에 DATA_SOURCE=live (또는 EDGE_MODE=all) 를 넣고 재시작하세요.",
    title: "이 노드가 데모(mock) 모드로 떠 있어 스토리지 화면의 값이 전부 가짜입니다",
    meaning: "이 노드가 데모(mock) 모드로 떠 있어 스토리지 화면의 값이 전부 가짜입니다. 운영 노드에서 찍히면 설정 사고입니다.",
    action: "운영 노드라면 portal.env 에 DATA_SOURCE=live 를 넣고 재시작하세요. 데모 노드라면 조치할 것이 없습니다." }),
  C({ id: "storage-db-disabled", tag: "storage-db", severity: "medium", category: "config", entity: 1, entityLabel: "원인",
    re: "SQLite 비활성\\((.*?)\\) — ",
    src: "server/src/storage/db.js", probe: "SQLite 비활성",
    sample: "[storage-db] SQLite 비활성(SQLITE_CANTOPEN: unable to open database file) — API 원문/시계열 DB 저장 없이 동작(최신 스냅샷만)",
    title: "스토리지 이력 DB 를 열지 못해 최신 스냅샷만으로 동작합니다",
    meaning: "스토리지 이력 DB 를 열지 못해 최신 스냅샷만으로 동작합니다. 용량 추이·증가량 보고서의 일 롤업이 쌓이지 않습니다.",
    action: "데이터 디렉터리 권한·여유 공간을 확인하고 재시작하세요. 증가량 보고서가 끊긴 기간은 소급되지 않습니다.",
    link: "#/tools/storage-growth", linkLabel: "스토리지 증가량" }),
  C({ id: "sansw-perf-push-fail", tag: "sanswitch-perf-push", severity: "medium", category: "network", entity: 1, entityLabel: "HTTP 상태",
    re: "중계 실패: (?:sanswitch-perf <- (\\d{3}))?",
    src: "server/src/sanswitch/perfPush.js", probe: "중계 실패:",
    sample: "[sanswitch-perf-push] 중계 실패: sanswitch-perf <- 403 (청크 1/3)",
    title: "엣지가 SAN 포트 사용량 표본을 중앙에 올리지 못했습니다",
    meaning: "엣지가 SAN 포트 사용량 표본을 중앙에 올리지 못했습니다. 403 은 토큰 거부, 413 은 크기 초과, 그 밖은 네트워크입니다. 표본은 엣지에 남아 다음 성공 때 이어서 올라갑니다.",
    action: "403 이면 포탈 점검의 토큰 점검으로 이 엣지의 중앙 토큰을 확인하고, 그 밖이면 통신 점검에서 엣지 → 중앙 push 링크를 확인하세요.",
    link: "#/tools/portal-check", linkLabel: "포탈 점검" }),
  C({ id: "sansw-perf-db-unavailable", tag: "sanswitch-perf", severity: "medium", category: "config",
    re: "DB 사용 불가\\(수집은 계속, 이력만 비활성\\): ",
    src: "server/src/sanswitch/perfDb.js", probe: "수집은 계속, 이력만 비활성",
    sample: "[sanswitch-perf] DB 사용 불가(수집은 계속, 이력만 비활성): SQLITE_CANTOPEN: unable to open database file",
    title: "SAN 포트 사용량 DB 를 열지 못해 이력 없이 동작합니다",
    meaning: "SAN 포트 사용량 DB 를 열지 못해 이력 없이 동작합니다. 포트 사용량 차트가 비고, 엣지면 중앙으로 올릴 표본도 없습니다.",
    action: "데이터 디렉터리 권한·여유 공간을 확인하고 재시작하세요.",
    link: "#/settings/sansw-perf", linkLabel: "SAN 스위치 포트 사용량" }),
  C({ id: "sansw-baseline-save-fail", tag: "sanswitch-baseline", severity: "medium", category: "data",
    re: "저장 실패: ",
    src: "server/src/sanswitch/errBaseline.js", probe: "저장 실패:",
    sample: "[sanswitch-baseline] 저장 실패: ENOSPC: no space left on device",
    title: "SAN 포트 에러 카운터 기준선을 파일에 쓰지 못했습니다",
    meaning: "SAN 포트 에러 카운터 기준선을 파일에 쓰지 못했습니다. 메모리에는 남지만 재시작하면 기준선이 사라져, 다음 월간 점검이 당월 신규 에러를 판정하지 못합니다.",
    action: "설정 디렉터리의 여유 공간·권한을 확인하세요. 해결 뒤 SAN 스위치 월간 점검을 다시 돌려 기준선을 저장하세요.",
    link: "#/tools/san-switch", linkLabel: "SAN 스위치 모니터링" }),
  C({ id: "idrac-poll-partial", tag: "idrac", severity: "medium", category: "stability",
    re: "poll: (\\d+)/(\\d+) 성공",
    src: "server/src/idrac/poller.js", probe: "poll:",
    sample: "[idrac] poll: 118/124 성공",
    title: "iDRAC 전력·센서 폴에서 일부 서버가 실패했습니다",
    meaning: "iDRAC 전력·센서 폴에서 일부 서버가 실패했습니다. 이 줄에는 어느 서버인지 없습니다(실패 서버는 화면의 서버별 오류에 있습니다).",
    action: "iDRAC 서버 등록 화면에서 오류가 표시된 서버의 연결·계정을 확인하세요. 실패 수가 매 주기 같으면 특정 서버의 고정 문제입니다.",
    link: "#/settings/idrac-admin", linkLabel: "iDRAC 서버 등록" }),
  C({ id: "idrac-power-insert-fail", tag: "idrac", severity: "high", category: "data",
    re: "전력 적재 실패: ",
    src: "server/src/idrac/poller.js", probe: "전력 적재 실패:",
    sample: "[idrac] 전력 적재 실패: SQLITE_FULL: database or disk is full",
    title: "폴한 전력 표본을 DB 에 쓰지 못했습니다",
    meaning: "폴한 전력 표본을 DB 에 쓰지 못했습니다. 그 주기의 전 서버 전력 이력이 빠져 추이·집계에 구멍이 생깁니다.",
    action: "SQLITE_FULL·ENOSPC 면 데이터 디스크를 확보하세요. 그 밖이면 표본 문구를 개발자에게 전달하세요.",
    link: "#/settings/diagnostics", linkLabel: "진단·로그" }),
  C({ id: "idrac-sqlite-fallback", tag: "idrac", severity: "medium", category: "config", entity: 1, entityLabel: "원인 코드",
    re: "node:sqlite 사용 불가\\((.*?)\\); NDJSON 폴백 사용",
    src: "server/src/idrac/db.js", probe: "node:sqlite 사용 불가",
    sample: "[idrac] node:sqlite 사용 불가(ERR_UNKNOWN_BUILTIN_MODULE); NDJSON 폴백 사용. SQLite를 쓰려면 NODE_OPTIONS=--experimental-sqlite 로 실행하세요.",
    title: "전력 DB 가 SQLite 대신 NDJSON 파일 폴백으로 동작합니다",
    meaning: "전력 DB 가 SQLite 대신 NDJSON 파일 폴백으로 동작합니다. 대규모에서 조회·집계가 느리고 시간당 롤업 이점이 없습니다.",
    action: "포탈의 Node 버전이 node:sqlite 를 지원하는지 확인하세요(오프라인 패키지의 번들 Node 사용 권장). 재시작 후 이 줄이 사라져야 합니다.",
    link: "#/settings/about", linkLabel: "About" }),
  C({ id: "idrac-scan-fail", tag: "idrac-scan", severity: "medium", category: "stability",
    re: "(?<!저장 )(?<!\\S)(?:백그라운드 스캔 )?실패: ",
    src: "server/src/idrac/scanPoller.js", probe: "실패:",
    sample: "[idrac-scan] 실패: fetch failed",
    title: "iDRAC 자동 발견(대역 스캔) 한 회차가 예외로 끝났습니다",
    meaning: "iDRAC 자동 발견(대역 스캔) 한 회차가 예외로 끝났습니다. 새로 설치된 서버가 이번 회차에 등록되지 않았습니다.",
    action: "iDRAC 스캔 로그에서 그 회차의 진행 기록을 확인하세요. 반복되면 스캔 대역·계정 설정을 점검하세요.",
    link: "#/settings/idrac-scan-log", linkLabel: "스캔 로그" }),
  C({ id: "idrac-scan-ranges-save-fail", tag: "idrac-scan-ranges", severity: "high", category: "data",
    re: "저장 실패: ",
    src: "server/src/idrac/scanRanges.js", probe: "저장 실패:",
    sample: "[idrac-scan-ranges] 저장 실패: EACCES: permission denied, open '/opt/portal/config/idrac-scan-ranges.json'",
    title: "iDRAC 스캔 대역·계정 설정을 파일에 쓰지 못했습니다",
    meaning: "iDRAC 스캔 대역·계정 설정을 파일에 쓰지 못했습니다. 화면에는 저장된 것처럼 보이지만(메모리에만 반영) 재시작하면 사라집니다.",
    action: "설정 디렉터리 권한·여유 공간을 고친 뒤 스캔 대역을 다시 저장하세요.",
    link: "#/settings/idrac-admin", linkLabel: "iDRAC 서버 등록" }),
  C({ id: "pdu-push-413", tag: "pdu-push", severity: "high", category: "data",
    re: "중앙이 본문 크기를 거부\\(413\\)\\. 스냅샷 (\\d+)건",
    src: "server/src/pdu/push.js", probe: "중앙이 본문 크기를 거부",
    sample: "[pdu-push] 중앙이 본문 크기를 거부(413). 스냅샷 40건 · JSON 1310KB — 중앙의 JSON_BODY_LIMIT 을 확인하세요.",
    title: "이 엣지의 PDU 스냅샷 전량이 중앙에서 크기 초과로 거부됐습니다",
    meaning: "이 엣지의 PDU 스냅샷 전량이 중앙에서 크기 초과로 거부됐습니다. 413 은 재시도되지 않아 그 법인 PDU 데이터가 중앙에 오지 않습니다.",
    action: "중앙 portal.env 의 JSON_BODY_LIMIT 을 늘리고 재시작하세요. 엣지 로그 화면에서 PDU push 상태를 확인하세요.",
    link: "#/tools/edge-log", linkLabel: "엣지 로그 · 진행상태" }),
  C({ id: "pdu-db-open-fail", tag: "pdu-db", severity: "medium", category: "config",
    re: "시계열 DB를 열 수 없습니다\\(시계열 비활성\\): ",
    src: "server/src/pdu/db.js", probe: "시계열 DB를 열 수 없습니다",
    sample: "[pdu-db] 시계열 DB를 열 수 없습니다(시계열 비활성): SQLITE_CANTOPEN: unable to open database file",
    title: "PDU 시계열 DB 를 열지 못해 전력·온도 추이가 쌓이지 않습니다(최신값만 보입니다).",
    meaning: "PDU 시계열 DB 를 열지 못해 전력·온도 추이가 쌓이지 않습니다(최신값만 보입니다).",
    action: "데이터 디렉터리 권한·여유 공간을 확인하고 재시작하세요.",
    link: "#/tools/pdu", linkLabel: "PDU 정보" }),
  C({ id: "pdu-threshold-eval-fail", tag: "pdu", severity: "high", category: "stability",
    re: "임계치 평가 실패: ",
    src: "server/src/pdu/poller.js", probe: "임계치 평가 실패:",
    sample: "[pdu] 임계치 평가 실패: Cannot read properties of undefined (reading 'kw')",
    title: "PDU 수집은 됐지만 임계치 판정 단계가 예외로 끝나 이번 주기에 전력·온도 초과 알림이 판정되지 않았습니다",
    meaning: "PDU 수집은 됐지만 임계치 판정 단계가 예외로 끝나 이번 주기에 전력·온도 초과 알림이 판정되지 않았습니다. 반복되면 초과가 있어도 알림이 나가지 않습니다.",
    action: "PDU 정보 화면의 임계치 설정을 확인하고, 반복되면 표본 문구를 개발자에게 전달하세요.",
    link: "#/tools/pdu", linkLabel: "PDU 정보" }),
  C({ id: "metrics-insert-fail", tag: "metrics", severity: "high", category: "data",
    re: "insert 실패: ",
    src: "server/src/metrics/sampler.js", probe: "insert 실패:",
    sample: "[metrics] insert 실패: SQLITE_FULL: database or disk is full",
    title: "지표 샘플(호스트·데이터스토어·온도 등)을 DB 에 쓰지 못했습니다",
    meaning: "지표 샘플(호스트·데이터스토어·온도 등)을 DB 에 쓰지 못했습니다. 그 주기의 전 지표 이력이 빠졌습니다.",
    action: "SQLITE_FULL·ENOSPC 면 데이터 디스크를 확보하거나 지표 수집 보존일을 줄이세요.",
    link: "#/settings/metrics", linkLabel: "지표 수집" }),
  C({ id: "vmperf-insert-fail", tag: "vmperf", severity: "medium", category: "data", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) insert 실패: ",
    src: "server/src/metrics/sampler.js", probe: "insert 실패:",
    sample: "[vmperf] vc-a insert 실패: SQLITE_BUSY: database is locked",
    title: "그 vCenter 의 VM 성능 표본을 vCenter 별 DB 파일에 쓰지 못했습니다",
    meaning: "그 vCenter 의 VM 성능 표본을 vCenter 별 DB 파일에 쓰지 못했습니다. 그 vCenter 의 이번 주기 VM 성능 이력이 빠졌습니다.",
    action: "디스크 여유·권한을 확인하세요. 특정 vCenter 만 반복되면 그 DB 파일(vmperf 폴더)의 손상 여부를 확인하세요.",
    link: "#/settings/metrics", linkLabel: "지표 수집" }),
  C({ id: "metrics-prune-fail", tag: "metrics", severity: "medium", category: "data",
    re: "(롤업 )?prune 실패: ",
    src: "server/src/metrics/sampler.js", probe: "prune 실패:",
    sample: "[metrics] prune 실패: SQLITE_FULL: database or disk is full",
    title: "보존기간이 지난 지표 행을 지우지 못했습니다",
    meaning: "보존기간이 지난 지표 행을 지우지 못했습니다. 반복되면 DB 가 계속 커집니다 — v2.451 장애 때처럼 디스크 부족(SQLITE_FULL)의 신호일 수 있습니다.",
    action: "데이터 디스크 여유를 확인하고, 지표 수집 설정의 원본 보존일을 줄이세요.",
    link: "#/settings/metrics", linkLabel: "지표 수집" }),
  C({ id: "metrics-sqlite-fallback", tag: "metrics", severity: "medium", category: "config", entity: 1, entityLabel: "원인 코드",
    re: "node:sqlite 불가\\((.*?)\\); NDJSON 폴백",
    src: "server/src/metrics/db.js", probe: "node:sqlite 불가",
    sample: "[metrics] node:sqlite 불가(ERR_UNKNOWN_BUILTIN_MODULE); NDJSON 폴백.",
    title: "지표 DB 가 SQLite 대신 NDJSON 폴백으로 동작합니다",
    meaning: "지표 DB 가 SQLite 대신 NDJSON 폴백으로 동작합니다. 대규모 환경에서 추이 조회가 느려지고 시간당 롤업이 없습니다.",
    action: "Node 가 node:sqlite 를 지원하는지 확인하세요(번들 Node 권장). 같은 원인으로 [ping]·[vclogs] 에도 같은 줄이 찍힙니다.",
    link: "#/settings/about", linkLabel: "About" }),
  C({ id: "vclogs-vc-fail", tag: "vclogs", severity: "medium", category: "stability", entity: 1, entityLabel: "vCenter id",
    re: "(\\S+) 수집 실패: ",
    src: "server/src/logs/poller.js", probe: "수집 실패:",
    sample: "[vclogs] vc-a 수집 실패: fetch failed",
    title: "그 vCenter 의 이벤트 로그 장기 보관 수집이 실패했습니다",
    meaning: "그 vCenter 의 이벤트 로그 장기 보관 수집이 실패했습니다. 다음 주기에 이어서 받지만, vCenter 의 이벤트 보존 기간을 넘기면 그 구간은 보관되지 않습니다.",
    action: "vCenter 연결 테스트로 그 vCenter 의 연결·계정을 확인하세요.",
    link: "#/settings/vclogs", linkLabel: "vCenter 로그 보관" }),
  C({ id: "svcmon-save-fail", tag: "svcmon", severity: "high", category: "data",
    re: "(?<!배치 원장 )저장 실패: ",
    src: "server/src/svcmon/store.js", probe: "저장 실패:",
    sample: "[svcmon] 저장 실패: ENOSPC: no space left on device",
    title: "성능점검 결과 저장 파일을 쓰지 못했습니다",
    meaning: "성능점검 결과 저장 파일을 쓰지 못했습니다. 메모리에는 남아 다음 저장 때 재시도하지만, 그 전에 재시작하면 최근 결과가 사라집니다.",
    action: "설정 디렉터리의 여유 공간·권한을 확인하세요.",
    link: "#/tools/svcmon-config", linkLabel: "Monitoring 설정" }),
  C({ id: "svcmon-worker-died", tag: "svcmon", severity: "medium", category: "stability", entity: 1, entityLabel: "워커 번호",
    re: "워커 #(\\d+) 종료\\((.*?)\\) — 다음 배치에서 재생성",
    src: "server/src/svcmon/pool.js", probe: "— 다음 배치에서 재생성",
    sample: "[svcmon] 워커 #2 종료(exit 1) — 다음 배치에서 재생성",
    title: "성능점검 워커 스레드가 죽었습니다",
    meaning: "성능점검 워커 스레드가 죽었습니다. 진행 중이던 점검은 인라인 폴백으로 넘어가고 다음 배치에서 워커를 다시 만듭니다. 반복되면 메인 이벤트 루프에서 점검이 돌아 UI 가 느려질 수 있습니다.",
    action: "같은 시각의 [svcmon:worker] uncaught 줄을 찾아 원인을 확인하세요. 반복되면 개발자에게 전달하세요.",
    link: "#/tools/svcmon-config", linkLabel: "Monitoring 설정" }),
  C({ id: "ping-targets-corrupt", tag: "ping", severity: "critical", category: "data",
    re: "대상 파일이 손상돼 읽지 못했습니다 — 원본을 보존했습니다",
    src: "server/src/ping/store.js", probe: "대상 파일이 손상돼 읽지 못했습니다 — 원본을 보존했습니다",
    sample: "[ping] 대상 파일이 손상돼 읽지 못했습니다 — 원본을 보존했습니다: Unexpected end of JSON input",
    title: "Ping 대상 파일(ping-targets.json)이 손상돼 대상 0개로 시작했습니다",
    meaning: "Ping 대상 파일(ping-targets.json)이 손상돼 대상 0개로 시작했습니다. 손상본은 .corrupt 로 보존했지만, 화면에서 대상을 추가·저장하는 순간 새 파일이 기존 목록을 대체합니다.",
    action: "대상을 새로 저장하기 전에 설정 디렉터리의 ping-targets.json.corrupt 파일을 확인해 복구하거나 포탈 백업에서 되돌리세요.",
    link: "#/settings/backup", linkLabel: "포탈 백업" }),
  C({ id: "partfault-scan-fail", tag: "partfault", severity: "high", category: "stability",
    re: "점검 실패: ",
    src: "server/src/partfault/poller.js", probe: "점검 실패:",
    sample: "[partfault] 점검 실패: SQLITE_BUSY: database is locked",
    title: "부품 장애 판정 한 회차가 실패했습니다",
    meaning: "부품 장애 판정 한 회차가 실패했습니다. 그 회차에 새 장애가 열리지 않았고 알림도 나가지 않았습니다.",
    action: "파트 장애 화면의 마지막 점검 시각을 확인하고, 반복되면 표본 문구를 개발자에게 전달하세요.",
    link: "#/tools/part-faults", linkLabel: "파트 장애(부품)" }),
  C({ id: "partfault-schema-reset", tag: "partfault", severity: "medium", category: "data", entity: 1, entityLabel: "DB 파일 경로",
    re: "(\\S+): 스키마 v(\\d+) → v(\\d+) — 파트 상태 (\\d+)행",
    src: "server/src/partfault/db.js", probe: ": 스키마 v",
    sample: "[partfault] /data/part-faults.db: 스키마 v1 → v2 — 파트 상태 812행·이벤트 3301행을 지우고 새로 시작합니다(파트 키 체계 변경)",
    title: "파트 장애 DB 의 키 체계가 바뀌어 옛 상태·이벤트를 지우고 새로 시작했습니다",
    meaning: "파트 장애 DB 의 키 체계가 바뀌어 옛 상태·이벤트를 지우고 새로 시작했습니다. 업그레이드 직후 1회는 설계된 동작이며, 열려 있던 장애는 다음 판정에서 다시 열립니다(알림이 다시 나갈 수 있습니다).",
    action: "업그레이드 직후 1회면 조치할 것이 없습니다. 재시작마다 반복되면 DB 파일이 계속 옛 버전으로 되돌아가는 원인(백업 복원 등)을 확인하세요.",
    link: "#/tools/part-faults", linkLabel: "파트 장애(부품)" }),
  C({ id: "partfault-push-413", tag: "partfault-push", severity: "high", category: "data",
    re: "중앙이 본문 크기를 거부\\(413\\)\\. 장비 (\\d+)대",
    src: "server/src/partfault/push.js", probe: "중앙이 본문 크기를 거부",
    sample: "[partfault-push] 중앙이 본문 크기를 거부(413). 장비 310대 · JSON 1420KB — 중앙의 BIG_JSON 등록 또는 PARTFAULT_PUSH_MAX_DEVICES 를 확인하세요.",
    title: "이 엣지의 부품 판정 보고가 중앙에서 크기 초과로 거부됐습니다",
    meaning: "이 엣지의 부품 판정 보고가 중앙에서 크기 초과로 거부됐습니다. 그 법인의 부품 장애가 중앙에 기록·알림되지 않습니다.",
    action: "중앙 버전이 part-faults 수신을 대용량(BIG_JSON)으로 받는지 확인하고, 엣지의 PARTFAULT_PUSH_MAX_DEVICES 를 조정하세요.",
    link: "#/tools/part-faults", linkLabel: "파트 장애(부품)" }),
  C({ id: "partfault-push-auth", tag: "partfault-push", severity: "high", category: "auth", entity: 1, entityLabel: "HTTP 상태",
    re: "실패: part-faults <- (40[13])",
    src: "server/src/partfault/push.js", probe: "part-faults <-",
    sample: "[partfault-push] 실패: part-faults <- 403",
    title: "중앙이 이 엣지의 부품 판정 보고를 인증 단계에서 거부했습니다",
    meaning: "중앙이 이 엣지의 부품 판정 보고를 인증 단계에서 거부했습니다. 그 법인의 부품 장애가 중앙에 오지 않습니다.",
    action: "포탈 점검의 토큰 점검으로 이 엣지의 중앙 토큰(개별 토큰 여부)을 확인하세요.",
    link: "#/tools/portal-check", linkLabel: "포탈 점검" }),
  C({ id: "partfault-push-fail", tag: "partfault-push", severity: "medium", category: "network",
    re: "실패: (?!part-faults <- 40[13])",
    src: "server/src/partfault/push.js", probe: "실패:",
    sample: "[partfault-push] 실패: fetch failed",
    title: "엣지가 부품 판정 보고를 중앙에 올리지 못했습니다(네트워크·중앙 오류). 다음 주기에 다시 보냅니다",
    meaning: "엣지가 부품 판정 보고를 중앙에 올리지 못했습니다(네트워크·중앙 오류). 다음 주기에 다시 보냅니다.",
    action: "통신 점검에서 이 엣지의 엣지 → 중앙 push 링크 단계를 확인하세요.",
    link: "#/tools/link-check", linkLabel: "통신 점검" }),
  C({ id: "horizon-tls-verify-off", tag: "horizon", severity: "medium", category: "config",
    re: "(?:⚠\\s*)?HTTPS 인증서 검증이 꺼져 있습니다",
    src: "server/src/horizon/horizon.js", probe: "HTTPS 인증서 검증이 꺼져 있습니다",
    sample: "[horizon] ⚠ HTTPS 인증서 검증이 꺼져 있습니다(기본값) — 커넥션 서버로 AD 계정이 전송되는 경로입니다. 사설 CA 를 신뢰시키고 HORIZON_TLS_VERIFY=true 로 켜는 것을 권장합니다.",
    title: "Horizon 커넥션 서버로 AD 계정을 보내는 경로에서 인증서를 검증하지 않습니다",
    meaning: "Horizon 커넥션 서버로 AD 계정을 보내는 경로에서 인증서를 검증하지 않습니다. 중간자가 AD 자격증명을 가로챌 수 있는 구성입니다(기동 시 1회 출력).",
    action: "커넥션 서버 인증서의 사설 CA 를 포탈 서버에 신뢰시키고 portal.env 에 HORIZON_TLS_VERIFY=true 를 넣은 뒤 재시작하세요." }),
  C({ id: "collector-deny-token-mismatch", tag: "collector", severity: "high", category: "auth", entity: 1, entityLabel: "요청 출발지 IP", edge: true,
    re: "인증 거부\\((?:[^)]+)\\) — src=(\\S+) · 토큰 불일치 · 요청토큰=",
    src: "server/src/collector/denyLog.js", probe: ") — src=",
    sample: "[collector] 인증 거부(export) — src=10.20.0.5 · 토큰 불일치 · 요청토큰=제공됨(len=32)",
    title: "이 엣지로 들어온 수집 요청의 X-Collector-Token 이 엣지 자신의 COLLECTOR_TOKEN 과 다릅니다",
    meaning: "이 엣지로 들어온 수집 요청의 X-Collector-Token 이 엣지 자신의 COLLECTOR_TOKEN 과 다릅니다. 요청을 보낸 곳이 중앙 포탈이면 중앙에 등록된 수집 토큰이 엣지 값과 어긋난 상태이고, 그 법인의 서버·전력·인벤토리가 중앙에 도착하지 않습니다. 같은 출발지는 30초에 한 줄만 찍힙니다.",
    action: "특수기능 › 포탈 점검 › 토큰 점검에서 해당 엣지의 지문(sha256 8자·길이·앞뒤 공백)을 대조하세요. 그다음 설정 › 수집 서버에서 그 엣지 항목의 토큰을 엣지 portal.env 의 COLLECTOR_TOKEN 과 같게 고치세요. 출발지가 중앙이 아니면 어떤 장비가 요청을 보내는지 확인하세요.",
    link: "#/tools/portal-check", linkLabel: "포탈 점검" }),
  C({ id: "collector-deny-no-header", tag: "collector", severity: "medium", category: "auth", entity: 1, entityLabel: "요청 출발지 IP", edge: true,
    re: "인증 거부\\((?:[^)]+)\\) — src=(\\S+) · 요청에 X-Collector-Token 없음",
    src: "server/src/collector/denyLog.js", probe: ") — src=",
    sample: "[collector] 인증 거부(export) — src=10.20.0.7 · 요청에 X-Collector-Token 없음 · 요청토큰=없음",
    title: "토큰 헤더가 없는 수집 요청을 거부했습니다",
    meaning: "토큰 헤더가 없는 수집 요청을 거부했습니다. 중앙의 수집 서버 항목에 토큰이 비어 있거나, 브라우저·스캐너·다른 도구가 수집 경로를 호출한 경우입니다.",
    action: "출발지 IP 가 중앙이면 설정 › 수집 서버에서 그 항목의 토큰을 채우세요. 모르는 출발지면 방화벽에서 수집 포트에 접근할 수 있는 대상을 좁히세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "collector-deny-token-unset", tag: "collector", severity: "high", category: "auth", entity: 1, entityLabel: "요청 출발지 IP", edge: true,
    re: "인증 거부\\((?:[^)]+)\\) — src=(\\S+) · COLLECTOR_TOKEN 미설정",
    src: "server/src/collector/denyLog.js", probe: ") — src=",
    sample: "[collector] 인증 거부(export) — src=10.20.0.5 · COLLECTOR_TOKEN 미설정(collector 비활성) · 요청토큰=제공됨(len=32)",
    title: "이 엣지의 portal.env 에 COLLECTOR_TOKEN 이 없어 수집 데이터 제공 기능이 꺼져 있습니다",
    meaning: "이 엣지의 portal.env 에 COLLECTOR_TOKEN 이 없어 수집 데이터 제공 기능이 꺼져 있습니다. 중앙의 요청은 모두 거부되므로 이 법인 데이터는 중앙에 도착하지 않습니다.",
    action: "엣지 portal.env 에 COLLECTOR_TOKEN 을 넣고 재시작하세요. 그다음 중앙의 설정 › 수집 서버에서 그 항목의 토큰을 같은 값으로 맞추세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "collector-pull-retry", tag: "collector", severity: "low", category: "network", entity: 1, entityLabel: "수집 서버 id",
    re: "(\\S+) 재시도 \\d+ \\(",
    src: "server/src/collector/puller.js", probe: "재시도",
    sample: "[collector] edge-kr01 재시도 1 (HTTP 503)",
    title: "중앙이 엣지 export 를 가져오다",
    meaning: "중앙이 엣지 export 를 가져오다 일시 오류가 나서 재시도했습니다. 재시도 안에서 성공하면 영향이 없습니다. 같은 엣지가 주기마다 찍히면 고지연·불안정 회선이거나 엣지가 과부하 상태입니다.",
    action: "같은 엣지가 반복되면 특수기능 › 통신 점검에서 그 엣지의 단계별(DNS·TCP·TLS·HTTP) 결과를 확인하세요.",
    link: "#/tools/link-check", linkLabel: "통신 점검" }),
  C({ id: "central-agent-mismatch", tag: "central", severity: "high", category: "auth", entity: 1, entityLabel: "토큰 소유 엣지",
    re: "agent 불일치 거부(?:\\(register-collector\\))? — 토큰=(\\S+) 요청=(?:\\S+)",
    src: "server/src/routes/central.js", probe: "register-collector",
    sample: "[central] agent 불일치 거부 — 토큰=EDGE-A 요청=EDGE-B (POST /inventory)",
    title: "엣지별 개별 토큰을 가진 요청이 다른 엣지 이름을 내세워 403 으로 막았습니다",
    meaning: "엣지별 개별 토큰을 가진 요청이 다른 엣지 이름을 내세워 403 으로 막았습니다. 대개 엣지 portal.env 의 AGENT_NAME 과 토큰을 발급한 엣지 이름이 서로 다른 설정 실수입니다. 이 상태에서는 그 엣지의 push 가 모두 거부됩니다.",
    action: "설정 › 수집 서버에서 토큰 발급 이름과 해당 엣지의 AGENT_NAME 을 대조하세요. 설정이 맞는데도 반복되면 토큰 유출을 의심하고 재발급하세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "central-self-register-reject", tag: "central", severity: "medium", category: "network", entity: 1, entityLabel: "엣지 이름",
    re: "엣지 자기등록 거부: (\\S+) — ",
    src: "server/src/routes/central.js", probe: "엣지 자기등록 거부:",
    sample: "[central] 엣지 자기등록 거부: edge-kr02 — 유도한 주소 http://10.20.0.5:4000 에 응답한 엣지가 'edge-kr01' (이 엣지 'edge-kr02' 아님). NAT/포워딩 뒤 엣지는 portal.env 에 EDGE_ADVERTISE_URL=http://<중앙에서 닿는 주소>:<포트> 를 지정하세요(중계 엣지의 포워딩 포트).",
    title: "요청 IP 로 만든 엣지 주소가 실제로 그 엣지에 닿지 않아 등록을 거부했습니다",
    meaning: "요청 IP 로 만든 엣지 주소가 실제로 그 엣지에 닿지 않아 등록을 거부했습니다. NAT·포트포워딩 뒤에 있는 엣지에서 흔히 생깁니다. 엣지는 30분 뒤 다시 시도합니다.",
    action: "해당 엣지 portal.env 의 EDGE_ADVERTISE_URL 에 중앙에서 닿는 주소를 지정하고 재시작하세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "central-self-register-unverified", tag: "central", severity: "low", category: "network", entity: 1, entityLabel: "엣지 이름",
    re: "엣지 자기등록: (\\S+) → .* ⚠ 미검증: ",
    src: "server/src/routes/central.js", probe: "엣지 자기등록:",
    sample: "[central] 엣지 자기등록: edge-kr01 → http://edge-kr01.example.local:4000 (v2.582.0) ⚠ 미검증: 유도한 주소 http://edge-kr01.example.local:4000 에 중앙이 닿지 못함(fetch failed). NAT/포워딩 뒤 엣지는 portal.env 에 EDGE_ADVERTISE_URL=http://<중앙에서 닿는 주소>:<포트> 를 지정하세요(중계 엣지의 포워딩 포트).",
    title: "관리자가 지정한 광고 주소(EDGE_ADVERTISE_URL)로 등록은 했지만, 중앙이 그 주소로 보낸 확인 요청은 성공하지 않았습니다",
    meaning: "관리자가 지정한 광고 주소(EDGE_ADVERTISE_URL)로 등록은 했지만, 중앙이 그 주소로 보낸 확인 요청은 성공하지 않았습니다. 이후 데이터 가져오기가 실패할 수 있습니다.",
    action: "설정 › 수집 서버에서 그 항목의 상태를 보고, 중앙에서 광고 주소에 실제로 닿는지 확인하세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "central-self-register-ok", tag: "central", severity: "info", category: "noise", entity: 1, entityLabel: "엣지 이름",
    re: "엣지 자기등록: (\\S+) → ",
    src: "server/src/routes/central.js", probe: "엣지 자기등록:",
    sample: "[central] 엣지 자기등록: edge-kr01 → http://10.20.0.5:4000 (v2.582.0)",
    title: "엣지 자기등록(재알림)이 정상 처리됐다는 기록입니다",
    meaning: "엣지 자기등록(재알림)이 정상 처리됐다는 기록입니다. 엣지는 기동할 때와 6시간마다 다시 알리므로 엣지 수만큼 주기적으로 찍힙니다.",
    action: "조치할 것이 없습니다." }),
  C({ id: "central-storage-drop", tag: "central", severity: "medium", category: "data", entity: 1, entityLabel: "엣지 이름",
    re: "storage-data: (\\S+) 미위임 deviceId \\d+건 드롭",
    src: "server/src/routes/central.js", probe: "storage-data:",
    sample: "[central] storage-data: EDGE-A 미위임 deviceId 3건 드롭(위조 방지)",
    title: "엣지가 보낸 스토리지 값 중 그 엣지에 위임되지 않은 장비 것을 버렸습니다",
    meaning: "엣지가 보낸 스토리지 값 중 그 엣지에 위임되지 않은 장비 것을 버렸습니다. 중앙과 엣지가 알고 있는 담당 엣지가 서로 다르고, 그 장비들은 중앙 화면에서 갱신되지 않습니다.",
    action: "특수기능 › 스토리지 모니터링에서 해당 장비의 담당 엣지(agent)를 확인하세요. 엣지가 바뀐 설정을 받았는지도 보세요(재시작하거나 다음 설정 pull 을 기다리면 받습니다).",
    link: "#/tools/storage-mon", linkLabel: "스토리지 모니터링" }),
  C({ id: "central-pdu-drop", tag: "central", severity: "medium", category: "data", entity: 1, entityLabel: "엣지 이름",
    re: "pdu-data: (\\S+) 미위임 id \\d+건 드롭",
    src: "server/src/routes/central.js", probe: "pdu-data:",
    sample: "[central] pdu-data: EDGE-A 미위임 id 2건 드롭(위조 방지)",
    title: "엣지가 보낸 PDU 값 중 그 엣지에 위임되지 않은 PDU 것을 버렸습니다",
    meaning: "엣지가 보낸 PDU 값 중 그 엣지에 위임되지 않은 PDU 것을 버렸습니다. 담당 엣지 지정이 어긋나 그 PDU 는 중앙에서 갱신되지 않습니다.",
    action: "특수기능 › PDU 에서 해당 PDU 의 담당 엣지를 확인하세요.",
    link: "#/tools/pdu", linkLabel: "PDU 정보" }),
  C({ id: "central-sanswitch-drop", tag: "central", severity: "medium", category: "data", entity: 1, entityLabel: "엣지 이름",
    re: "sanswitch-(?:data|perf): (\\S+) 미위임 deviceId (?:표본 )?\\d+건 드롭",
    src: "server/src/routes/central.js", probe: "미위임 deviceId",
    sample: "[central] sanswitch-perf: EDGE-A 미위임 deviceId 표본 120건 드롭(위조 방지)",
    title: "엣지가 보낸 SAN 스위치 상태·포트 사용량 중 그 엣지에 위임되지 않은 스위치 것을 버렸습니다",
    meaning: "엣지가 보낸 SAN 스위치 상태·포트 사용량 중 그 엣지에 위임되지 않은 스위치 것을 버렸습니다. 담당 엣지 지정이 어긋나 그 스위치는 중앙 화면에서 갱신되지 않거나 차트가 빕니다.",
    action: "특수기능 › SAN 스위치에서 해당 장비의 담당 엣지를 확인하세요.",
    link: "#/tools/san-switch", linkLabel: "SAN 스위치 모니터링" }),
  C({ id: "central-ipscan-drop", tag: "central", severity: "medium", category: "data", entity: 1, entityLabel: "엣지 이름",
    re: "ip-scan-result: (\\S+) 배정 범위 밖 IP \\d+개 드롭",
    src: "server/src/routes/central.js", probe: "ip-scan-result:",
    sample: "[central] ip-scan-result: EDGE-A 배정 범위 밖 IP 14개 드롭(위조 방지)",
    title: "엣지의 IP 스캔 결과 중 그 엣지에 배정된 범위 밖의 IP 를 버렸습니다",
    meaning: "엣지의 IP 스캔 결과 중 그 엣지에 배정된 범위 밖의 IP 를 버렸습니다. 중앙에 설정된 배정 범위가 엣지가 실제로 스캔한 범위보다 좁습니다.",
    action: "특수기능 › 엣지 스캔 작업에서 그 엣지의 배정 범위를 확인하세요.",
    link: "#/tools/agent-scans", linkLabel: "에이전트 작업" }),
  C({ id: "central-rma-ip-deny", tag: "central", severity: "high", category: "auth", entity: 1, entityLabel: "엣지 이름",
    re: "rma-poll: (\\S+) 허용되지 않은 출처 IP (?:\\S+) 거부",
    src: "server/src/routes/central.js", probe: "허용되지 않은 출처 IP",
    sample: "[central] rma-poll: EDGE-A 허용되지 않은 출처 IP 10.99.1.20 거부",
    title: "원격 명령(RMA) 요청이 그 법인의 접속 허용 IP 목록에 없는 주소에서 왔습니다",
    meaning: "원격 명령(RMA) 요청이 그 법인의 접속 허용 IP 목록에 없는 주소에서 왔습니다. 엣지 IP 가 바뀌었거나 그 엣지의 토큰을 다른 곳에서 쓰고 있다는 뜻입니다. 거부되는 동안에는 그 법인으로 원격 명령이 전달되지 않습니다.",
    action: "특수기능 › 원격 명령에서 접속 허용 IP 를 확인하세요. 엣지 IP 가 바뀐 적이 없으면 그 엣지의 토큰을 재발급하세요.",
    link: "#/tools/rma", linkLabel: "원격 명령 실행 (RMA)" }),
  C({ id: "central-curuser-rejected", tag: "central", severity: "medium", category: "stability", entity: 1, entityLabel: "엣지 이름",
    re: "curuser 수신: agent=(\\S+) chunk=\\S+ records=\\d+ 거부=",
    src: "server/src/routes/central.js", probe: "curuser 수신: agent=",
    sample: "[central] curuser 수신: agent=EDGE-A chunk=0/1 records=12 거부=vc-branch-02",
    title: "현재 사용자 보고 중 그 엣지가 담당하지 않는 vCenter(또는 목 vCenter)의 값을 버렸습니다",
    meaning: "현재 사용자 보고 중 그 엣지가 담당하지 않는 vCenter(또는 목 vCenter)의 값을 버렸습니다. '거부=' 뒤에 적힌 vCenter 는 현재 사용자 화면에서 갱신되지 않습니다.",
    action: "설정 › vCenter 등록·관리에서 거부된 vCenter 의 담당 엣지(site 수집)를 확인하세요.",
    link: "#/settings/vcenter-admin", linkLabel: "vCenter 등록·관리" }),
  C({ id: "central-curuser-recv", tag: "central", severity: "info", category: "noise", entity: 1, entityLabel: "엣지 이름",
    re: "curuser 수신: agent=(\\S+) ",
    src: "server/src/routes/central.js", probe: "curuser 수신: agent=",
    sample: "[central] curuser 수신: agent=EDGE-A chunk=0/1 records=40",
    title: "현재 사용자 보고를 정상 수신했다는 기록입니다",
    meaning: "현재 사용자 보고를 정상 수신했다는 기록입니다. 수집을 켠 엣지마다 수집 주기(기본 10분)에 한 번씩 찍힙니다.",
    action: "조치할 것이 없습니다." }),
  C({ id: "central-vmseries-recv", tag: "central", severity: "info", category: "noise", entity: 1, entityLabel: "엣지 이름",
    re: "vmseries 수신: agent=(\\S+) ",
    src: "server/src/routes/central.js", probe: "vmseries 수신: agent=",
    sample: "[central] vmseries 수신: agent=EDGE-A vc=vc-branch-01 chunk=0/2 spikes=310 cover=5200",
    title: "VM 실시간 스파이크 데이터 청크를 정상 수신했다는 기록입니다",
    meaning: "VM 실시간 스파이크 데이터 청크를 정상 수신했다는 기록입니다. 수집을 켠 vCenter 마다 주기(기본 50분)에 청크 수만큼 찍힙니다.",
    action: "조치할 것이 없습니다." }),
  C({ id: "central-mock-inventory-pruned", tag: "central", severity: "medium", category: "data",
    re: "저장돼 있던 목\\(가짜\\) 인벤토리 \\d+건 제거",
    src: "server/src/central/inventory.js", probe: "저장돼 있던 목",
    sample: "[central] 저장돼 있던 목(가짜) 인벤토리 2건 제거: vc-us-east, vc-eu-west — 엣지가 DATA_SOURCE=auto 로 폴백했거나 구버전이라 올라온 데이터입니다.",
    title: "중앙이 기동하면서, 엣지가 올려 둔 목(데모) 인벤토리를 지웠습니다",
    meaning: "중앙이 기동하면서, 엣지가 올려 둔 목(데모) 인벤토리를 지웠습니다. 어느 엣지가 vCenter 접속에 실패해 DATA_SOURCE=auto 설정대로 목 데이터로 폴백했거나 구버전이었다는 뜻입니다.",
    action: "해당 엣지 portal.env 에 DATA_SOURCE=live 를 넣고 vCenter 접속을 확인하세요. 특수기능 › 포탈 점검 › 인벤토리 점검에서 거부(mock) 기록도 함께 보세요.",
    link: "#/tools/portal-check", linkLabel: "포탈 점검" }),
  C({ id: "central-inventory-corrupt", tag: "central", severity: "medium", category: "data", entity: 1, entityLabel: "파일 경로",
    re: "(\\S+central-inventory\\.json) 파싱 실패\\(",
    src: "server/src/central/inventory.js", probe: "central-inventory",
    sample: "[central] /opt/portal/config/central-inventory.json 파싱 실패(Unexpected end of JSON input) — /opt/portal/config/central-inventory.json.corrupt.1790000000000로 보존하고 빈 인벤토리로 시작합니다.",
    title: "위임 vCenter 인벤토리 캐시 파일이 손상돼 빈 캐시로 시작했습니다",
    meaning: "위임 vCenter 인벤토리 캐시 파일이 손상돼 빈 캐시로 시작했습니다. 캐시이므로 각 엣지의 다음 push 로 자동 복구되지만, 그때까지 위임 법인 화면이 비어 보입니다.",
    action: "엣지 push 주기(기본 수 분) 안에 복구되는지 인벤토리 점검 화면에서 확인하세요. 디스크가 가득 찼거나 비정상 종료가 있었는지 등 손상 원인도 확인하세요.",
    link: "#/tools/portal-check", linkLabel: "포탈 점검" }),
  C({ id: "central-store-corrupt", tag: "central", severity: "high", category: "data", entity: 1, entityLabel: "파일 이름",
    re: "(central-agent-users\\.json|central-agent-gpu-guest\\.json|agent-assignments\\.json|agent-results\\.json) 파싱 실패: ",
    src: "server/src/central/assignments.js", probe: "agent-assignments",
    sample: "[central] agent-assignments.json 파싱 실패: Unexpected token } in JSON at position 812",
    title: "엣지에 배포할 설정 파일(배정·사용자·GPU 게스트 자격증명·결과) 중 하나가 손상돼 빈 값으로 시작했습니다",
    meaning: "엣지에 배포할 설정 파일(배정·사용자·GPU 게스트 자격증명·결과) 중 하나가 손상돼 빈 값으로 시작했습니다. 손상본은 .corrupt 파일로 보존됐지만, 이 상태로 저장하면 엣지에 빈 설정이 배포됩니다. 같은 사건의 [atomicWrite] 줄이 바로 앞에 함께 찍힙니다.",
    action: "설정 디렉터리의 손상본(.corrupt.*)으로 복구하거나 포탈 백업에서 되돌린 뒤 재시작하세요. 복구하기 전에는 해당 배포 화면에서 저장하지 마세요.",
    link: "#/settings/backup", linkLabel: "포탈 백업" }),
  C({ id: "central-token-store-corrupt", tag: "central-token", severity: "critical", category: "data",
    re: "central-agent-tokens\\.json 파싱 실패\\(",
    src: "server/src/central/agentTokens.js", probe: "central-agent-tokens",
    sample: "[central-token] central-agent-tokens.json 파싱 실패(Unexpected end of JSON input) — 손상본을 .corrupt로 보존하고 빈 목록으로 시작합니다.",
    title: "엣지별 개별 토큰 파일이 손상돼 빈 목록으로 시작했습니다",
    meaning: "엣지별 개별 토큰 파일이 손상돼 빈 목록으로 시작했습니다. 개별 토큰을 쓰는 모든 엣지의 push 와 설정 pull 이 403 으로 거부됩니다.",
    action: "설정 디렉터리의 central-agent-tokens.json.corrupt.* 로 복구하거나 포탈 백업에서 되돌린 뒤 재시작하세요. 복구할 수 없으면 설정 › 수집 서버에서 토큰을 재발급해 각 엣지에 넣어야 합니다.",
    link: "#/settings/backup", linkLabel: "포탈 백업" }),
  C({ id: "http-unhandled-413", tag: "", severity: "high", category: "data", entity: 1, entityLabel: "API 경로",
    re: "^unhandled (?:POST|PUT|PATCH) (\\S+) 413: PayloadTooLargeError",
    src: "server/src/index.js", probe: "unhandled",
    sample: "unhandled POST /api/central/sanswitch-data 413: PayloadTooLargeError: request entity too large",
    title: "요청 본문이 크기 한도를 넘어 거부했습니다",
    meaning: "요청 본문이 크기 한도를 넘어 거부했습니다. 엣지는 413 을 재시도하지 않으므로 그 push 의 데이터는 오류 표시 없이 전부 사라집니다. 원인은 둘 중 하나입니다. 큰 push 경로가 큰 한도(BIG_JSON)에 등록되지 않았거나, 본문이 16MB 를 넘었습니다. 등록된 경로라도 요청 토큰이 무효면 큰 한도가 적용되지 않아 1MB 에서 413 이 납니다. 따라서 토큰 문제가 413 으로 보일 수 있습니다.",
    action: "경로를 보고 어느 엣지 기능의 push 인지 확인한 뒤, 같은 시각의 토큰 거부 기록을 먼저 보세요. 토큰이 정상이면 경로와 크기를 개발자에게 전달하세요. JSON_BODY_LIMIT 은 큰 한도 경로에만 적용됩니다.",
    link: "#/tools/portal-check", linkLabel: "포탈 점검" }),
  C({ id: "http-unhandled-5xx", tag: "", severity: "high", category: "stability", entity: 1, entityLabel: "API 경로",
    re: "^unhandled (?:GET|POST|PUT|PATCH|DELETE) (\\S+) 5\\d\\d: ",
    src: "server/src/index.js", probe: "unhandled",
    sample: "unhandled GET /api/tools/storage-growth 500: TypeError: periods.map is not a function",
    title: "라우트에서 예외가 나서 전역 오류 처리기가 500 으로 응답했습니다",
    meaning: "라우트에서 예외가 나서 전역 오류 처리기가 500 으로 응답했습니다. 그 화면에는 오류가 표시됩니다. 같은 경로가 반복되면 코드 결함입니다.",
    action: "경로와 예외 문구(스택)를 개발자에게 전달하세요. 서버 성능 측정에서 같은 경로의 오류율도 함께 확인하세요.",
    link: "#/settings/perf-monitor", linkLabel: "서버 성능 측정" }),
  C({ id: "edgelog-worker-413", tag: "edgelog-worker", severity: "medium", category: "data", edge: true,
    re: "중앙이 본문 크기를 거부\\(413\\) — 로그 (?:\\S+)줄",
    src: "server/src/agent/edgeLogWorker.js", probe: "중앙이 본문 크기를 거부",
    sample: "[edgelog-worker] 중앙이 본문 크기를 거부(413) — 로그 400줄. EDGELOG 한도를 확인하세요.",
    title: "중앙이 요청한 엣지 로그 회신을 크기 초과로 거부했습니다",
    meaning: "중앙이 요청한 엣지 로그 회신을 크기 초과로 거부했습니다. 중앙의 엣지 로그 화면에 이 엣지의 결과가 오지 않습니다.",
    action: "특수기능 › 엣지 로그에서 가져올 줄 수를 줄여 다시 요청하세요. 중앙이 구버전이면 업그레이드하세요.",
    link: "#/tools/edge-log", linkLabel: "엣지 로그 · 진행상태" }),
  C({ id: "linkcheck-worker-413", tag: "linkcheck-worker", severity: "medium", category: "data", edge: true,
    re: "중앙이 본문 크기를 거부\\(413\\) — 링크 (?:\\d+)개",
    src: "server/src/agent/linkCheckWorker.js", probe: "중앙이 본문 크기를 거부",
    sample: "[linkcheck-worker] 중앙이 본문 크기를 거부(413) — 링크 480개. 중앙의 BIG_JSON 등록을 확인하세요.",
    title: "중앙이 통신 점검 결과 보고를 크기 초과로 거부했습니다",
    meaning: "중앙이 통신 점검 결과 보고를 크기 초과로 거부했습니다. 중앙의 통신 점검 화면에서 이 엣지가 측정하는 링크는 '측정 없음'으로 남습니다.",
    action: "중앙과 엣지의 버전을 맞추세요. 반복되면 개발자에게 전달하세요.",
    link: "#/tools/link-check", linkLabel: "통신 점검" }),
  C({ id: "linkcheck-worker-403", tag: "linkcheck-worker", severity: "medium", category: "stability", edge: true,
    re: "보고 실패: HTTP 403 — 이 엣지의 개별 토큰",
    src: "server/src/agent/linkCheckWorker.js", probe: "— 이 엣지의 개별 토큰(설정 > 엣지 토큰)이 필요합니다.",
    sample: "[linkcheck-worker] 보고 실패: HTTP 403 — 이 엣지의 개별 토큰(설정 > 엣지 토큰)이 필요합니다.",
    title: "통신 점검 보고는 엣지별 개별 토큰으로만 받는데, 이 엣지는 공유 토큰으로 보냈습니다",
    meaning: "통신 점검 보고는 엣지별 개별 토큰으로만 받는데, 이 엣지는 공유 토큰으로 보냈습니다. 이 상태에서는 엣지 쪽 통신 점검이 전혀 동작하지 않습니다.",
    action: "설정 › 수집 서버에서 이 엣지의 개별 토큰을 발급하고, 엣지 portal.env 의 CENTRAL_TOKEN 에 넣은 뒤 재시작하세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "svcmon-push-413-shrink", tag: "svcmon-push", severity: "low", category: "data", entity: 1, entityLabel: "줄인 청크 행 수", edge: true,
    re: "413 — 청크를 (\\d+)행으로 줄여 재시도",
    src: "server/src/agent/svcmonPush.js", probe: "행으로 줄여 재시도",
    sample: "[svcmon-push] 413 — 청크를 250행으로 줄여 재시도합니다.",
    title: "성능점검 결과 push 가 크기 초과로 거부돼 청크를 절반으로 줄여 자동으로 재시도했습니다",
    meaning: "성능점검 결과 push 가 크기 초과로 거부돼 청크를 절반으로 줄여 자동으로 재시도했습니다. 자동으로 처리되므로 한 번뿐이면 영향이 없습니다.",
    action: "주기마다 반복되면 중앙에서 이 경로가 큰 한도 등록에서 빠졌거나 토큰이 무효인 상태입니다. 중앙 로그에서 같은 시각의 413 줄을 확인하세요.",
    link: "#/tools/svcmon-config", linkLabel: "Monitoring 설정" }),
  C({ id: "idrac-scan-agent-poll-fail", tag: "idrac-scan-agent", severity: "medium", category: "network", entity: 1, entityLabel: "실패 종류", edge: true,
    re: "중앙 잡 인출 실패\\((auth|http|timeout|unreachable)\\)",
    src: "server/src/agent/idracScanWorker.js", probe: "unreachable",
    sample: "[idrac-scan-agent] 중앙 잡 인출 실패(auth) HTTP 403 — 1회 연속. 개별 CENTRAL_TOKEN·엣지 이름·중앙 URL 을 확인하세요.",
    title: "중앙에서 iDRAC 위임 스캔 작업을 가져오지 못했습니다",
    meaning: "중앙에서 iDRAC 위임 스캔 작업을 가져오지 못했습니다. 실패 종류가 auth 이면 토큰이 거부된 것이고, 이 법인에서 누른 스캔은 계속 대기 상태로 남습니다. 첫 실패 때와 이후 20회마다 한 줄씩만 찍힙니다.",
    action: "auth 이면 설정 › 수집 서버에서 이 엣지의 개별 토큰과 AGENT_NAME 을 확인하세요. timeout·unreachable 이면 중앙 URL 과 회선을 확인하세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "self-register-fail", tag: "self-register", severity: "medium", category: "network", entity: 1, entityLabel: "HTTP 상태", edge: true,
    re: "중앙 (?:등록 실패\\((\\d+)\\)|연결 실패): ",
    src: "server/src/agent/selfRegister.js", probe: "연결 실패",
    sample: "[self-register] 중앙 등록 실패(400): 요청 IP가 루프백입니다(중앙이 프록시 뒤). 엣지에 EDGE_ADVERTISE_URL(urlHint)를 지정하세요. — 30분 뒤 재시도(설정을 고치면 재시작으로 즉시)",
    title: "엣지가 중앙에 자기 등록을 하지 못했습니다",
    meaning: "엣지가 중앙에 자기 등록을 하지 못했습니다. 400 은 중앙이 설정 오류로 거부한 것이고 30분 뒤 다시 시도합니다. '연결 실패'는 중앙에 닿지 않는 것입니다. 등록되지 않으면 중앙은 이 엣지의 데이터를 가져오지 않습니다.",
    action: "메시지에 적힌 사유에 맞춰 엣지 portal.env(EDGE_ADVERTISE_URL·CENTRAL_URL·CENTRAL_TOKEN)를 고치고 재시작하세요. 그다음 중앙의 설정 › 수집 서버에 항목이 생겼는지 확인하세요.",
    link: "#/settings/collectors", linkLabel: "수집 서버(원격)" }),
  C({ id: "inv-push-mock-skip", tag: "inv-push", severity: "high", category: "config", entity: 1, entityLabel: "vCenter id", edge: true,
    re: "(\\S+) 는 목\\(가짜\\) 데이터라 중앙에 보내지 않습니다",
    src: "server/src/agent/inventoryPush.js", probe: "데이터라 중앙에 보내지 않습니다",
    sample: "[inv-push] vc-branch-01 는 목(가짜) 데이터라 중앙에 보내지 않습니다 — vCenter 접속이 안 돼 auto 폴백된 상태입니다. portal.env 에 DATA_SOURCE=live 를 넣고 vCenter 접속 정보를 확인·재시작하세요.",
    title: "이 엣지가 vCenter 에 접속하지 못해 목 데이터로 폴백했기 때문에, 이 vCenter 의 인벤토리를 중앙에 보내지 않습니다",
    meaning: "이 엣지가 vCenter 에 접속하지 못해 목 데이터로 폴백했기 때문에, 이 vCenter 의 인벤토리를 중앙에 보내지 않습니다. 중앙 화면에서 이 법인 데이터가 오래된 값으로 남거나 비어 보입니다.",
    action: "엣지 portal.env 에 DATA_SOURCE=live 를 넣고, 설정 › vCenter 연결 테스트로 접속을 확인한 뒤 재시작하세요.",
    link: "#/settings/vcenter-test", linkLabel: "vCenter 연결 테스트" }),
  C({ id: "logq-agent-poll-fail", tag: "logq-agent", severity: "medium", category: "network", entity: 1, entityLabel: "실패 사유", edge: true,
    re: "인출 실패: (중앙이 토큰을 거부했습니다\\(403\\)|중앙 응답 HTTP \\d+)",
    src: "server/src/agent/logQueryWorker.js", probe: "중앙이 토큰을 거부했습니다",
    sample: "[logq-agent] 인출 실패: 중앙이 토큰을 거부했습니다(403) — CENTRAL_TOKEN 을 확인하세요.",
    title: "중앙에서 vCenter 로그 연합 조회 요청을 가져오지 못했습니다",
    meaning: "중앙에서 vCenter 로그 연합 조회 요청을 가져오지 못했습니다. 이 엣지가 맡은 vCenter 의 로그 조회는 중앙 화면에서 대기 상태로 남습니다.",
    action: "403 이면 엣지의 CENTRAL_TOKEN 을 확인하세요. 설정 › vCenter 로그 보관에서 해당 법인의 조회가 끝나는지 확인하세요.",
    link: "#/settings/vclogs", linkLabel: "vCenter 로그 보관" }),
  C({ id: "gpu-guest-push-fail", tag: "gpu-guest-push", severity: "medium", category: "network", entity: 1, entityLabel: "실패 사유", edge: true,
    re: "실패: (.+)$",
    src: "server/src/agent/gpuGuestPush.js", probe: "실패:",
    sample: "[gpu-guest-push] 실패: gpu-guest -> 403",
    title: "GPU 게스트 수집 결과를 중앙에 올리지 못했습니다",
    meaning: "GPU 게스트 수집 결과를 중앙에 올리지 못했습니다. 중앙 GPU 화면에서 이 법인의 값이 오래된 값으로 남습니다.",
    action: "403 이면 엣지 토큰을, 연결 오류면 중앙 URL 과 회선을 확인하세요. 설정 › GPU 수집 진단에서 이 엣지의 마지막 수신 시각을 보세요.",
    link: "#/settings/gpu-guest-diag", linkLabel: "GPU 수집 진단" }),
  C({ id: "gpu-guest-push-sent", tag: "gpu-guest-push", severity: "info", category: "noise", edge: true,
    re: "sent → \\S+ hosts=(?:\\d+) vms=(?:\\d+)",
    src: "server/src/agent/gpuGuestPush.js", probe: "sent →",
    sample: "[gpu-guest-push] sent → https://central.example.local:4000 hosts=11 vms=40",
    title: "GPU 게스트 결과 push 가 성공했다는 기록입니다",
    meaning: "GPU 게스트 결과 push 가 성공했다는 기록입니다. 대상이 0이어도 진단용으로 주기마다(기본 60초) 보내므로 엣지 로그에서 가장 자주 찍히는 줄 중 하나입니다.",
    action: "조치할 것이 없습니다." }),
  C({ id: "listen-eaddrinuse", tag: "listen", severity: "critical", category: "config", entity: 1, entityLabel: "포트",
    re: "포트 (\\d+) 이미 사용 중\\(EADDRINUSE\\)",
    src: "server/src/index.js", probe: "EADDRINUSE",
    sample: "[listen] 포트 4000 이미 사용 중(EADDRINUSE). 다른 프로세스가 점유 중이거나 PORT를 바꾸세요.",
    title: "포트를 이미 다른 프로세스가 쓰고 있어 포탈이 기동하지 못하고 종료했습니다",
    meaning: "포트를 이미 다른 프로세스가 쓰고 있어 포탈이 기동하지 못하고 종료했습니다. systemd 가 재시작을 반복하므로 같은 줄이 이어서 찍힙니다. 이전 포탈 프로세스가 남아 있거나 다른 서비스가 같은 포트를 쓰는 경우입니다.",
    action: "서버에서 그 포트를 쓰는 프로세스를 찾아 정리하거나 portal.env 의 PORT 를 바꾸세요." }),
  C({ id: "listen-eacces", tag: "listen", severity: "critical", category: "config", entity: 1, entityLabel: "포트",
    re: "포트 (\\d+) 권한 거부\\(EACCES\\)",
    src: "server/src/index.js", probe: "권한 거부(EACCES). 1024 미만 특권포트입니다. PORT를 10",
    sample: "[listen] 포트 443 권한 거부(EACCES). 1024 미만 특권포트입니다. PORT를 1024 이상(예: 4000)으로 설정하세요. (portal.env의 PORT 확인)",
    title: "권한 없이 1024 미만 특권 포트를 열려다",
    meaning: "권한 없이 1024 미만 특권 포트를 열려다 실패해 포탈이 기동하지 못했습니다.",
    action: "portal.env 의 PORT 를 1024 이상으로 바꾸고, 443 은 앞단 프록시에서 받으세요." }),
  C({ id: "start-poller-fail", tag: "start", severity: "high", category: "stability",
    re: "폴러 기동 실패: ",
    src: "server/src/index.js", probe: "폴러 기동 실패:",
    sample: "[start] 폴러 기동 실패: Cannot read properties of undefined (reading 'intervalMs')",
    title: "기동할 때 폴러 하나가 예외로 시작되지 못했습니다",
    meaning: "기동할 때 폴러 하나가 예외로 시작되지 못했습니다. 그 폴러가 맡은 수집은 재시작 전까지 전혀 돌지 않습니다. 어느 폴러인지는 예외 문구로 판단합니다.",
    action: "예외 문구를 개발자에게 전달하고, 포탈을 재시작해 같은 오류가 다시 나는지 확인하세요.",
    link: "#/settings/diagnostics", linkLabel: "진단·로그" }),
  C({ id: "shutdown-signal", tag: "shutdown", severity: "info", category: "noise", entity: 1, entityLabel: "신호",
    re: "(SIG[A-Z]+) 수신 — 새 연결을 멈추고",
    src: "server/src/index.js", probe: "수신 — 새 연결을 멈추고",
    sample: "[shutdown] SIGTERM 수신 — 새 연결을 멈추고 진행 중 요청을 마무리합니다(최대 10초).",
    title: "종료 신호를 받아 정상 종료 절차를 시작했습니다",
    meaning: "종료 신호를 받아 정상 종료 절차를 시작했습니다. 업그레이드나 systemctl restart 에서 나오는 정상 기록입니다. 이 줄 없이 기동 배너만 다시 찍혔다면 OOM 강제 종료 같은 비정상 종료입니다.",
    action: "관리자가 재시작하지 않았는데도 반복되면 설정 › 업그레이드의 자동 적용 이력과 서버 메모리를 확인하세요.",
    link: "#/settings/upgrade", linkLabel: "⬆ 업그레이드" }),
  C({ id: "loop-lag-severe", tag: "loop-lag", severity: "high", category: "perf",
    re: "이벤트루프 지연 max=(?:[5-9]\\d{3}|\\d{5,})ms",
    src: "server/src/util/loopLag.js", probe: "— 이 구간 동기 작업(수집 파싱/집계/bulk write)이 메인 루프",
    sample: "[loop-lag] 최근 30s 이벤트루프 지연 max=7420ms p99=6900ms mean=210.4ms — 이 구간 동기 작업(수집 파싱/집계/bulk write)이 메인 루프를 막았을 수 있음",
    title: "메인 이벤트 루프가 5초 이상 멈췄습니다",
    meaning: "메인 이벤트 루프가 5초 이상 멈췄습니다. 그동안 모든 API 응답·화면·수집이 함께 멈췄고, 재진입 가드 때문에 다음 폴링 차례를 건너뛰었을 수 있습니다.",
    action: "서버 성능 측정의 멈춤(hang) 기록에서 같은 시각에 돌던 작업을 확인하세요. 반복되면 그 시각의 태그 줄과 함께 개발자에게 전달하세요.",
    link: "#/settings/perf-monitor", linkLabel: "서버 성능 측정" }),
  C({ id: "loop-lag", tag: "loop-lag", severity: "medium", category: "perf",
    re: "이벤트루프 지연 max=(?:\\d+)ms p99=",
    src: "server/src/util/loopLag.js", probe: "ms p99=",
    sample: "[loop-lag] 최근 30s 이벤트루프 지연 max=820ms p99=640ms mean=12.3ms — 이 구간 동기 작업(수집 파싱/집계/bulk write)이 메인 루프를 막았을 수 있음",
    title: "최근 측정 구간에서 이벤트 루프가 임계값(기본 500ms) 이상 멈췄습니다",
    meaning: "최근 측정 구간에서 이벤트 루프가 임계값(기본 500ms) 이상 멈췄습니다. 그동안 화면 응답이 느려집니다. 대량 수집 데이터를 파싱할 때 가끔 한 번씩 생기는 것은 흔합니다.",
    action: "빈도가 늘면 서버 성능 측정에서 멈춤 기록과 느린 요청을 확인하세요.",
    link: "#/settings/perf-monitor", linkLabel: "서버 성능 측정" }),
  C({ id: "auth-disabled", tag: "auth", severity: "critical", category: "auth", entity: 1, entityLabel: "익명 역할",
    re: "인증이 비활성\\(AUTH_ENABLED=false\\) — 모든 요청이 익명 '([^']+)' 권한",
    src: "server/src/auth/auth.js", probe: "AUTH_ENABLED=false",
    sample: "[auth] ⚠ 인증이 비활성(AUTH_ENABLED=false) — 모든 요청이 익명 'admin' 권한으로 처리됩니다. 운영 환경에서는 인증을 켜거나 AUTH_DISABLED_ROLE=viewer 로 제한하세요.",
    title: "로그인 없이 모든 요청을 익명 역할로 처리합니다",
    meaning: "로그인 없이 모든 요청을 익명 역할로 처리합니다. 기본 역할이 admin 이므로 포탈에 접속할 수 있는 누구나 설정을 바꾸고 원격 명령을 실행할 수 있습니다.",
    action: "운영 서버라면 portal.env 에서 AUTH_ENABLED 를 켜고 재시작하세요. 시험용이라면 AUTH_DISABLED_ROLE=viewer 로 권한을 낮추세요.",
    link: "#/settings/security-self-check", linkLabel: "보안 자가진단" }),
  C({ id: "auth-secret-ephemeral", tag: "auth", severity: "high", category: "auth",
    re: "AUTH_SECRET 미설정 \\+ 시크릿 파일 쓰기 실패",
    src: "server/src/auth/auth.js", probe: "AUTH_SECRET 미설정",
    sample: "[auth] ⚠ AUTH_SECRET 미설정 + 시크릿 파일 쓰기 실패(EACCES: permission denied) — 프로세스 랜덤 시크릿 사용(재시작 시 전원 재로그인). CONFIG_DIR 쓰기 권한 또는 AUTH_SECRET env 를 확인하세요.",
    title: "세션 서명 키를 파일에 저장하지 못해 임시 키로 동작합니다",
    meaning: "세션 서명 키를 파일에 저장하지 못해 임시 키로 동작합니다. 재시작할 때마다 모든 사용자가 로그아웃됩니다. 설정 디렉터리에 쓸 권한이 없다면 다른 설정도 저장되지 않습니다.",
    action: "설정 디렉터리(CONFIG_DIR)의 소유자와 권한을 고치거나, portal.env 에 AUTH_SECRET 을 지정하고 재시작하세요.",
    link: "#/settings/security-self-check", linkLabel: "보안 자가진단" }),
  C({ id: "auth-no-otp-admin", tag: "auth", severity: "high", category: "auth",
    re: "OTP 가 등록된 admin 계정이 없습니다",
    src: "server/src/auth/auth.js", probe: "OTP 가 등록된 admin 계정이 없습니다",
    sample: "[auth] ⚠ OTP 가 등록된 admin 계정이 없습니다 — admin/operator 는 비밀번호로 로그인할 수 없습니다(OTP 전용).",
    title: "OTP 전용 정책인데 OTP 를 등록한 관리자가 없어 아무 관리자도 로그인할 수 없습니다",
    meaning: "OTP 전용 정책인데 OTP 를 등록한 관리자가 없어 아무 관리자도 로그인할 수 없습니다. 이어지는 줄에 서버 콘솔에서 등록하는 절차가 찍힙니다.",
    action: "서버에서 안내된 otp-enroll 도구로 첫 관리자의 OTP 를 등록하세요. OTP_ROLE_ENFORCE=false 로 정책을 임시 해제하는 것은 긴급할 때만 쓰세요.",
    link: "#/settings/session-security", linkLabel: "세션 보안" }),
  C({ id: "auth-users-corrupt", tag: "auth", severity: "critical", category: "data",
    re: "Failed to parse users\\.json: ",
    src: "server/src/auth/auth.js", probe: "Failed to parse users",
    sample: "[auth] Failed to parse users.json: Unexpected token , in JSON at position 1204",
    title: "사용자 계정 파일이 손상됐습니다",
    meaning: "사용자 계정 파일이 손상됐습니다. 손상본은 .corrupt 파일로 보존됐고, 이어서 기본 admin 계정 하나만 새로 만들어지므로 기존 계정으로는 로그인할 수 없습니다.",
    action: "설정 디렉터리의 users.json.corrupt.* 나 포탈 백업으로 users.json 을 복구하고 재시작하세요. 복구하기 전에는 계정을 새로 만들지 마세요. 새로 만든 파일이 원본을 덮어씁니다.",
    link: "#/settings/backup", linkLabel: "포탈 백업" }),
  C({ id: "auth-seed-admin", tag: "auth", severity: "medium", category: "auth",
    re: "users\\.json이 없어 기본 관리자 \"admin\"을 시드",
    src: "server/src/auth/auth.js", probe: "json이 없어 기본 관리자 \"admin\"을 시드",
    sample: "[auth] users.json이 없어 기본 관리자 \"admin\"을 시드했습니다 — DEFAULT_ADMIN_PASSWORD로 시드.",
    title: "사용자 파일이 없어 기본 admin 계정을 만들었습니다",
    meaning: "사용자 파일이 없어 기본 admin 계정을 만들었습니다. 처음 설치한 경우에는 정상입니다. 운영 중인 포탈에서 보이면 users.json 이 사라졌거나 설정 디렉터리가 바뀐 것입니다.",
    action: "운영 중이라면 설정 디렉터리 경로(CONFIG_DIR)가 바뀌지 않았는지 확인하고, 포탈 백업에서 users.json 을 복구해야 하는지 판단하세요.",
    link: "#/settings/users", linkLabel: "메인포탈 사용자 관리" }),
  C({ id: "perm-corrupt", tag: "perm", severity: "high", category: "data",
    re: "permissions\\.json 파싱 실패: ",
    src: "server/src/auth/permissions.js", probe: "permissions",
    sample: "[perm] permissions.json 파싱 실패: Unexpected end of JSON input",
    title: "역할별·사용자별 권한 파일이 손상돼 기본 권한으로 동작합니다",
    meaning: "역할별·사용자별 권한 파일이 손상돼 기본 권한으로 동작합니다. 관리자가 막아 둔 도구가 다시 열렸거나, 허용 목록으로 제한한 사용자의 제한이 풀렸을 수 있습니다.",
    action: "설정 디렉터리의 permissions.json.corrupt.* 나 포탈 백업으로 복구하세요. 복구하기 전에는 사용자 관리 화면에서 저장하지 마세요.",
    link: "#/settings/users", linkLabel: "메인포탈 사용자 관리" }),
  C({ id: "secrets-decrypt-fail", tag: "secrets", severity: "high", category: "data",
    re: "자격증명 복호 실패\\(",
    src: "server/src/security/secretVault.js", probe: "자격증명 복호 실패",
    sample: "[secrets] ⚠ 자격증명 복호 실패(Unsupported state or unable to authenticate data) — 빈 값으로 대체. 키(secrets-key/SECRETS_KEY) 변경·유실 여부를 확인하고 해당 계정 비밀번호를 재입력하세요.",
    title: "암호화해 저장한 장비·계정 비밀번호를 복호화하지 못해 빈 값으로 대체했습니다",
    meaning: "암호화해 저장한 장비·계정 비밀번호를 복호화하지 못해 빈 값으로 대체했습니다. 그 비밀번호를 쓰는 수집(vCenter·iDRAC·스토리지 등)은 모두 인증에 실패합니다. 같은 원인은 한 번만 찍힙니다.",
    action: "설정 › 자격증명 저장 방식에서 키 상태를 확인하세요. 키 파일(secrets-key)이 바뀌었거나 없어졌다면 원래 파일로 되돌리고, 되돌릴 수 없으면 해당 계정의 비밀번호를 다시 입력하세요.",
    link: "#/settings/secrets", linkLabel: "자격증명 저장 방식" }),
  C({ id: "secrets-key-write-fail", tag: "secrets", severity: "high", category: "data",
    re: "키 파일 쓰기 실패\\(",
    src: "server/src/security/secretVault.js", probe: "키 파일 쓰기 실패",
    sample: "[secrets] ⚠ 키 파일 쓰기 실패(EACCES: permission denied) — 임시 메모리 키 사용. 이 상태로 암호화 저장 시 재시작 후 복호가 불가능합니다. CONFIG_DIR 권한 또는 SECRETS_KEY env 를 확인하세요.",
    title: "비밀 암호화 키를 파일에 저장하지 못해 메모리에만 있는 키로 동작합니다",
    meaning: "비밀 암호화 키를 파일에 저장하지 못해 메모리에만 있는 키로 동작합니다. 이 상태에서 암호화해 저장한 비밀번호는 재시작 후에 복호화할 수 없습니다.",
    action: "재시작하기 전에 설정 디렉터리 권한을 고치거나 SECRETS_KEY 를 지정하세요. 그 전에는 자격증명 저장 방식을 암호화로 바꾸지 마세요.",
    link: "#/settings/secrets", linkLabel: "자격증명 저장 방식" }),
  C({ id: "ssrf-rebind-block", tag: "ssrf", severity: "high", category: "network", entity: 1, entityLabel: "호스트 이름",
    re: "DNS 리바인딩 차단: (\\S+) — ",
    src: "server/src/util/ssrfLookup.js", probe: "DNS 리바인딩 차단:",
    sample: "[ssrf] DNS 리바인딩 차단: storage-a.example.local — 링크로컬/메타데이터 주소는 사용할 수 없습니다.",
    title: "등록된 장비나 엣지의 이름이 접속하는 순간 루프백·메타데이터 같은 차단 대역 주소로 풀려서 연결을 막았습니다",
    meaning: "등록된 장비나 엣지의 이름이 접속하는 순간 루프백·메타데이터 같은 차단 대역 주소로 풀려서 연결을 막았습니다. DNS 설정 오류이거나 DNS 리바인딩 공격 시도입니다. 그 장비의 수집은 실패합니다.",
    action: "해당 이름의 DNS 레코드를 확인하세요. 그 주소가 의도한 것이라면 등록 화면에서 IP 로 등록하세요.",
    link: "#/settings/security-self-check", linkLabel: "보안 자가진단" }),
  C({ id: "wan-tls-insecure", tag: "wan", severity: "medium", category: "config",
    re: "WAN_TLS_INSECURE=true — 중앙↔엣지 HTTPS 인증서 검증이 비활성",
    src: "server/src/util/resilientFetch.js", probe: "WAN_TLS_INSECURE=true — 중앙↔엣지 HTTPS 인증서 검증이 비활성",
    sample: "[wan] ⚠ WAN_TLS_INSECURE=true — 중앙↔엣지 HTTPS 인증서 검증이 비활성입니다(자체서명 엣지 호환용). 가능하면 사설 CA를 신뢰시키고 이 옵션을 끄세요.",
    title: "중앙과 엣지 사이의 HTTPS 인증서를 검증하지 않습니다",
    meaning: "중앙과 엣지 사이의 HTTPS 인증서를 검증하지 않습니다. 중간자 공격으로 토큰과 수집 데이터를 가로챌 수 있습니다.",
    action: "사설 CA 를 신뢰 저장소에 넣고 portal.env 의 WAN_TLS_INSECURE 를 끄세요.",
    link: "#/settings/security-self-check", linkLabel: "보안 자가진단" }),
  C({ id: "emergency-stop-on", tag: "emergency-stop", severity: "high", category: "stability", entity: 1, entityLabel: "승인자",
    re: "긴급중단 ON — 승인: (.+)$",
    src: "server/src/security/emergencyStop.js", probe: "긴급중단 ON",
    sample: "[emergency-stop] 긴급중단 ON — 승인: admin-a + admin-b",
    title: "관리자 2명의 승인으로 긴급중단(전역 수집 정지)이 켜졌습니다",
    meaning: "관리자 2명의 승인으로 긴급중단(전역 수집 정지)이 켜졌습니다. 다음 주기부터 vCenter 폴링·GPU 게스트·iDRAC 전력 등 모든 백그라운드 수집이 멈춥니다. 화면은 마지막 스냅샷을 계속 보여 주므로 값이 점점 오래된 값이 됩니다. 이 상태는 재시작해도 유지됩니다.",
    action: "의도한 조치인지 승인자에게 확인하세요. 상황이 끝나면 특수기능 › 셧다운 화면에서 2인 승인으로 해제하세요.",
    link: "#/tools/shutdown", linkLabel: "긴급중단" }),
  C({ id: "certs-expiring", tag: "certs", severity: "medium", category: "network",
    re: "만료/임박 인증서 (\\d+)건 발견",
    src: "server/src/security/certMonitor.js", probe: "만료/임박 인증서",
    sample: "[certs] 만료/임박 인증서 3건 발견",
    title: "감시 중인 TLS 인증서 가운데 이미 만료됐거나 곧 만료되는 것이 있습니다",
    meaning: "감시 중인 TLS 인증서 가운데 이미 만료됐거나 곧 만료되는 것이 있습니다. 만료되면 그 장비나 서비스에 접속할 수 없습니다.",
    action: "특수기능 › 인증서 만료에서 대상 인증서와 남은 일수를 확인하고 갱신하세요.",
    link: "#/tools/cert-expiry", linkLabel: "인증서 만료 감시" }),
  C({ id: "upgrade-sha-reject", tag: "upgrade", severity: "high", category: "config",
    re: "원격 번들(?:에 sha256이 없어| sha256 불일치)",
    src: "server/src/upgrade/bundleSource.js", probe: "sha256 불일치",
    sample: "[upgrade] 원격 번들 sha256 불일치 — 손상/변조 가능(기대 3f9a1c2b7d4e…, 실제 9b2e0d11aa05…). 푸시를 거부했습니다.",
    title: "엣지로 보낼 업그레이드 번들의 무결성 검증에 실패해 푸시를 거부했습니다",
    meaning: "엣지로 보낼 업그레이드 번들의 무결성 검증에 실패해 푸시를 거부했습니다. 전송 중에 파일이 손상됐거나, 미러의 번들과 목록 파일이 서로 맞지 않습니다. 이 상태에서는 엣지가 업그레이드되지 않습니다.",
    action: "설정 › 업그레이드에서 원격 소스를 다시 받아 보세요. 미러를 쓴다면 versions.json 과 번들이 같은 버전인지 확인하세요.",
    link: "#/settings/upgrade", linkLabel: "⬆ 업그레이드" }),
  C({ id: "upgrade-unverified", tag: "upgrade", severity: "medium", category: "config",
    re: "(?:X-Bundle-)?[Ss]ha256 없이 .*UPGRADE_ALLOW_UNVERIFIED=true",
    src: "server/src/upgrade/upgrade.js", probe: "UPGRADE_ALLOW_UNVERIFIED=true",
    sample: "[upgrade] ⚠ sha256 없이 설치(UPGRADE_ALLOW_UNVERIFIED=true) — 무결성 미검증 번들. 신뢰 미러에서만 사용하세요.",
    title: "무결성 검증 없이 업그레이드 번들을 받거나 설치했습니다",
    meaning: "무결성 검증 없이 업그레이드 번들을 받거나 설치했습니다. 누군가 변조한 번들이라도 그대로 실행될 수 있습니다.",
    action: "공식 릴리스나 sha256 을 제공하는 미러를 쓰고, portal.env 의 UPGRADE_ALLOW_UNVERIFIED 를 끄세요.",
    link: "#/settings/upgrade", linkLabel: "⬆ 업그레이드" }),
  C({ id: "upgrade-tick-error", tag: "upgrade", severity: "medium", category: "stability",
    re: "tick error: ",
    src: "server/src/upgrade/manager.js", probe: "tick error:",
    sample: "[upgrade] tick error: fetch failed (ENOTFOUND github.com)",
    title: "주기적인 자동 업그레이드 확인이 실패했습니다",
    meaning: "주기적인 자동 업그레이드 확인이 실패했습니다. 폐쇄망이라 원격 소스에 닿지 않으면 주기마다 찍힙니다. 이 상태에서는 새 버전이 자동으로 적용되지 않습니다.",
    action: "설정 › 업그레이드에서 원격 소스와 감시 폴더 설정을 확인하세요. 폐쇄망이면 원격 소스를 끄고 오프라인 번들을 쓰세요.",
    link: "#/settings/upgrade", linkLabel: "⬆ 업그레이드" }),
  C({ id: "upgrade-auto-apply", tag: "upgrade", severity: "info", category: "noise",
    re: "새 버전 감지 — 적용 후 재시작합니다",
    src: "server/src/upgrade/manager.js", probe: "새 버전 감지 — 적용 후 재시작합니다",
    sample: "[upgrade] 새 버전 감지 — 적용 후 재시작합니다",
    title: "자동 업그레이드가 새 버전을 적용하고 재시작합니다",
    meaning: "자동 업그레이드가 새 버전을 적용하고 재시작합니다. 바로 뒤에 [shutdown] 줄과 기동 배너가 이어지는 것이 정상입니다.",
    action: "조치할 것이 없습니다. 재시작한 뒤 About 화면에서 버전이 올라갔는지 확인하세요.",
    link: "#/settings/about", linkLabel: "About" }),
  C({ id: "backup-fail", tag: "backup", severity: "high", category: "stability", entity: 1, entityLabel: "백업 계기",
    re: "(\\S+) 백업 실패: ",
    src: "server/src/backup/settings.js", probe: "백업 실패:",
    sample: "[backup] schedule 백업 실패: ENOSPC: no space left on device",
    title: "정기(schedule) 자동 백업이나 설정 변경(change) 시 자동 백업이 실패했습니다",
    meaning: "정기(schedule) 자동 백업이나 설정 변경(change) 시 자동 백업이 실패했습니다. 이후에 바뀐 설정은 백업에 없습니다.",
    action: "설정 › 포탈 백업에서 백업 경로·NFS 마운트·여유 공간을 확인하고, 수동 백업이 되는지 시험하세요.",
    link: "#/settings/backup", linkLabel: "포탈 백업" }),
  C({ id: "mail-send-fail", tag: "mail", severity: "medium", category: "stability", entity: 1, entityLabel: "메일 종류",
    re: "(?:^|\\] )([^\\]]+?) 발송 실패: ",
    src: "server/src/mail/service.js", probe: "발송 실패:",
    sample: "[mail] 알림(임계·장애) 발송 실패: 535 5.7.8 Authentication failed",
    title: "SMTP 단계에서 메일 발송이 실패했습니다",
    meaning: "SMTP 단계에서 메일 발송이 실패했습니다. 알림 메일이었다면 그 알림은 전달되지 않았습니다.",
    action: "설정 › 메일 발송에서 테스트 발송을 해 SMTP 대화(인증·STARTTLS)를 확인하고, 계정이나 서버 설정을 고치세요.",
    link: "#/settings/mail", linkLabel: "메일 발송" }),
  C({ id: "mail-settings-corrupt", tag: "mail", severity: "high", category: "data",
    re: "설정 로드 실패 — 원본을 \\.corrupt 로 보존하고 기본값으로 시작",
    src: "server/src/mail/settings.js", probe: "corrupt 로 보존하고 기본값으로 시작",
    sample: "[mail] 설정 로드 실패 — 원본을 .corrupt 로 보존하고 기본값으로 시작합니다: Unexpected end of JSON input",
    title: "메일 설정 파일이 손상돼 기본값으로 시작했습니다",
    meaning: "메일 설정 파일이 손상돼 기본값으로 시작했습니다. SMTP 계정과 수신자가 비어 있으므로 메일이 하나도 발송되지 않습니다.",
    action: "설정 디렉터리의 손상본이나 포탈 백업으로 복구하세요. 복구하기 전에 메일 설정 화면에서 저장하면 원본을 덮어씁니다.",
    link: "#/settings/mail", linkLabel: "메일 발송" }),
  C({ id: "daily-report-fail", tag: "daily-report", severity: "medium", category: "stability", entity: 1, entityLabel: "실패 사유",
    re: "발송 실패 — (.+) \\(다음 틱에 재시도\\)",
    src: "server/src/reports/dailyReport.js", probe: "다음 틱에 재시도",
    sample: "[daily-report] 발송 실패 — 수신자가 없습니다 (다음 틱에 재시도)",
    title: "일일 헬스체크 리포트 발송이 실패했습니다",
    meaning: "일일 헬스체크 리포트 발송이 실패했습니다. 1분마다 다시 시도하므로 원인이 해결될 때까지 같은 줄이 반복됩니다.",
    action: "설정 › 알림에서 일일 리포트 수신자를, 설정 › 메일 발송에서 SMTP 설정을 확인하세요.",
    link: "#/settings/alerts", linkLabel: "알림" }),
];
